### ISSUE TITLE
xud.sh to handle operations after installation

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#10]
`xud.sh` also handles starting the environment after e.g. a reboot of the system:
E.g. after reboot, simply running `xud.sh`
* checks if data directories and all configs exist, if not jump to installation
* check if all docker containers are up, if not start them and open xucli bash in xud container, exit

**Comment by reliveyy** [comment]
> check if all docker containers are up, if not start them and open xucli bash in xud container, exit

The bash in xud container can only access `xucli`. Are you sure you want to open this bash after installation. And if you open a interactive bash then that means it will take over your operating system's  standard input(0), output(1), and error(2), moreover you cannot exit anyway until the user type `exit` or `logout` in that xud bash.

**Comment by kilrau** [comment]
Yes, I would print "Starting xucli, exit by typing exit".

On Jun 5, 2019 9:39 AM, Yang Yang <notifications@github.com> wrote:

check if all docker containers are up, if not start them and open xucli bash in xud container, exit

The bash in xud container can only access xucli. Are you sure you want to open this bash after installation. And if you open a interactive bash then that means it will take over your operating system's standard input(0), output(1), and error(2), moreover you cannot exit anyway until the user type exit or logout in that xud bash.

**Comment by kilrau** [comment]
can't test this neither due to https://github.com/ExchangeUnion/xud-docker/issues/11

**Comment by kilrau** [comment]
Mostly done, details in future issues
