### ISSUE TITLE
xud-docker.log doesn't contain logs

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#101]
I just ran simnet for a while and all that was in `xud-docker.log`  is docker-compose stuff, nothing from xud,lnd or raiden. Logs in client folders, e.g. `~/.xud-docker/simnet/data/xud/logs/xud.log` exist and have content as one would expect.

```
Pulling ltcd   ...
Pulling lndbtc ...
Pulling lndltc ...
Pulling raiden ...
Pulling xud    ...
^[[4A^[[2K^MPulling lndbtc ... pulling from exchangeunion/lnd^M^[[4B^[[4A^[[2K^MPulling lndbtc ... digest: sha256:b15e5926eca682f1c7...$
Creating simnet_raiden_1 ...
Creating simnet_lndbtc_1 ...
Creating simnet_xud_1    ...
Creating simnet_lndltc_1 ...
Creating simnet_ltcd_1   ...
^[[4A^[[2K^MCreating simnet_lndbtc_1 ... ^[[32mdone^[[0m^M^[[4B^[[5A^[[2K^MCreating simnet_raiden_1 ... ^[[32mdone^[[0m^M^[[5B^[[1A^[[2$
```

**Comment by kilrau** [comment]
Could have to do with https://github.com/ExchangeUnion/xud-docker/issues/26 so that the scripts can't access the log files:

```
kilrau@K-Yoga:~/.xud-docker/simnet/data/lndbtc$ ls -la
total 40
drwxr-xr-x 4 root root 4096 Jul 22 14:09 .
drwxr-xr-x 8 root root 4096 Jul 22 14:09 ..
drwx------ 4 root root 4096 Jul 22 14:09 data
drwx------ 3 root root 4096 Jul 22 14:09 logs
-rw-r--r-- 1 root root  696 Jul 22 14:09 tls.cert
-rw------- 1 root root  227 Jul 22 14:09 tls.key
kilrau@K-Yoga:~/.xud-docker/simnet/data/lndbtc$ cd logs
bash: cd: logs: Permission denied
```

**Comment by rsercano** [comment]
May I give up on this, I put more hours to this than probably someone else who's more familiar like @reliveyy

**Comment by kilrau** [comment]
You may ;)

**Comment by reliveyy** [comment]
Here is the conclution from the voice call today: we simplify this task by just removing useless `docker-compose` part from xud-docker.log and DO NOT combine containers log in realtime. What we do is we collect each containers' log when user type `report` in xudctl shell.
