### ISSUE TITLE
Simnet env | lnd showing OutOfSync even if both lndbtc and xud restarted manually

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#104]
Steps to reproduce:

1. On AWS instance, install required version of docker and docker-compose
2. Prepare the environment and run the script as per [https://github.com/ExchangeUnion/xud/wiki/Docker](url)
3. Select Simnet environment either by typing the name or selecting the number (here, it is 1)
4. Run "getinfo" command
5. Validate error 
6. Restart lndbtc by "restart lndbtc"
7. Restart xud by "restart xud"
8. Again run "getinfo"
9. Validate error

Actual Result: At step 5 & 9 --> it shows error "lnd is OutOfSync" and peer as "0"

Here is the visual evidence for the same

https://drive.google.com/file/d/1_FF0CZogZq3LQEk7pessPjHa0Db13AQG/view?usp=sharing

**Comment by kilrau** [comment]
Fixed by now.
