### ISSUE TITLE
Testnet env | Not able to connect node manually hence not able to proceed further with trading

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#105]
As per given instruction at issue [https://github.com/ExchangeUnion/xud/issues/1116](url), I am unable to connect to the node manually and it shows an error "Unavailable"

Please check the screencast here - https://drive.google.com/file/d/1XlTkH1Cpeai3BQzKGyXZ08DvyyeKAP2T/view?usp=sharing

**Comment by kilrau** [comment]
This is fixed for me. Connection on init and also manual works:
```
testnet > listpeers
D0806 17:44:32.868754692      45 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
{
  "peersList": [
    {
      "address": "xud1.testnet.exchangeunion.com:8885",
      "nodePubKey": "02ee43f389523d7947e6a456eeb70f8429535f216654d1b1fdc753e48a96ca1469",
      "lndPubKeysMap": [
        [
          "BTC",
          "0259ca079c6a1dc47fa6f869c88e1630886d1c3e6437c9f892d44cd21c2b5f3492"
        ],
        [
          "LTC",
          "022636dbad74e1af260c7394583b497db8049b94468ae4f5d41773c9e02c98e173"
        ]
      ],
      "inbound": false,
      "pairsList": [
        "LTC/BTC"
      ],
      "xudVersion": "1.0.0-testnet.1",
      "secondsConnected": 26,
      "raidenAddress": "0x6e5bAc85719f59565d44FA0673bc91B87Af6F58f"
    }
  ]
}
testnet > connect 02ee43f389523d7947e6a456eeb70f8429535f216654d1b1fdc753e48a96ca1469@xud1.testnet.exchangeunion.com:8885
D0806 17:44:47.741651685      65 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
Error: 6 ALREADY_EXISTS: node 02ee43f389523d7947e6a456eeb70f8429535f216654d1b1fdc753e48a96ca1469 at xud1.testnet.exchangeunion.com:8885 already connected
```

Could you confirm? @fagunbhavsar

**Comment by fagunbhavsar** [comment]
@kilrau Sorry for the delay. Here was the last time I came across Testnet issue along with the logs

https://www.dropbox.com/home/ExchangeUnion_Testing_11282019

[xud-docker_testnet.log](https://github.com/ExchangeUnion/xud-docker/files/4138843/xud-docker_testnet.log)

**Comment by kilrau** [comment]
Thanks @fagunbhavsar , the issue is clear. I see the timestamps are from November 2019. Could you try our all-new docker setup by restarting your environment (`down`, `exit`, `bash xud.sh`) and accepting the update prompt? This also includes new versions of bitcoind, lnd, geth and xud (`1.0.0-beta`).

Testnet is working fine for us here and we want it to work for you too!
