### ISSUE TITLE
Automation testing

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#114]
Developers can run `tools/test <network>` to do automation testing on their local machine. I suggest to use `vagrant` as the local testing infrastructure and `python` as the testing programming language. Writing testing cases for a bash-like project could be a challenge. But it should be easy to add new testing cases in the future.

BDD supports:
1. https://github.com/voiski/bash_spec
2. https://github.com/pytest-dev/pytest-bdd
3. https://github.com/behave/behave

### Network burden:
Creating vagrant virtual machines repeatly could waste too much time on docker installation. So a local repository proxy for ubuntu/centos/alpine could shorten the testing period. And it is same for the blockchain data downloading process.

### CPU burden:
Running vagrant or docker locally for testing will consume your CPU resources. If we do not limit the CPU usage for testing tasks it could consume all your CPU and your computer will be very laggy to do code editing.

**Comment by reliveyy** [comment]
We can use `docker save` and `docker load` to transfer the images data locally

**Comment by kilrau** [comment]
Largely bash specific, which we don't have anymore. Could you add some more details on how you would setup a testing framework with today's environment? @reliveyy
