### ISSUE TITLE
Comparing images' branch label before pulling

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#118]
The xud script always pull images from cloud not matter it is upgrade or first start. This cause problems when you build your local image and want to try it with xud script. So a better approach to do pulling is that you can comparing the local and cloud images `com.exchangeunion.image.branch` label. Cloud image will always have branch "master" while local image's label is your feature branch name.

**Comment by kilrau** [comment]
I believe https://github.com/ExchangeUnion/xud-docker/pull/151 takes care of local testing of local branches, correct? If so, please close here @reliveyy
