### ISSUE TITLE
../main.sh: illegal option -- b

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#131]
Not critical, since a recognized illegal character doesn't upgrade. Probably caused by an outdated `main.sh`, since the environment wasn't restarted in several days.

```
A new version is available. Would you like to upgrade (Warning: this will restart your environment and cancel all open orders)? Y/n?n
../main.sh: illegal option -- b
```

**Comment by reliveyy** [comment]
I think this issue is already fixed. https://github.com/ExchangeUnion/xud-docker/commit/8ae2bd7db7a84d065b3557951a2d9ca13f00dfc6#diff-0e14a25824529e9df0c89de977ddd046L22

**Comment by kilrau** [comment]
Ok, will reopen if I see it again. Thanks!
