### ISSUE TITLE
Automatically build "latest" xud image when xud master is updated

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#132]
This issue is about an automated build of the xud docker image with dockerhub or travis every time a commit is pushed to xud master.

Simnet & Testnet only. NOT mainnet.

Dockerhub tag `latest`.

**Comment by reliveyy** [comment]
It has been done outside of this xud-docker project on Google Cloud instance.

**Comment by reliveyy** [comment]
> It has been done outside of this xud-docker project on Google Cloud instance.

And it worthwhile to try with GitHub actions.

**Comment by kilrau** [comment]
Let's try

**Comment by kilrau** [comment]
Since we spent quite some time asking for and building/pushing for "latest" image, I'd say this is pretty important. Let's do it in this cycle for 1.0.0-beta!

**Comment by kilrau** [comment]
simnet, testnet use tag `latest`, mainnet uses tag of the latest release

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud-docker/issues/300
