### ISSUE TITLE
Configurable: restart=no / always

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#15]
Make restart policy configurable:
set to "no" or "always" for all containers based on user input (https://github.com/ExchangeUnion/xud-docker/issues/30).

`xud.sh` should be the one point of entry and handle upping all containers and also restart if one of them fails.

**Comment by reliveyy** [comment]
For now docker restart lnd containers only because lnd will crash unexpectedly in some cases. @kilrau

**Comment by kilrau** [comment]
Yeah sure, but it also starts it automatically after system reboot which some/most users don't want, also the restart has problems, see https://github.com/ExchangeUnion/xud-docker/issues/15

**Comment by kilrau** [comment]
After restart there are always these 3 containers up.
```
kilrau@K-Yoga:~$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                          PORTS                      NAMES
725322b20c95        exchangeunion/lnd:0.6.1-beta   "./entrypoint.sh --a…"   22 hours ago        Restarting (1) 33 seconds ago                              testnet_lndltc_1
720c18035922        exchangeunion/raiden:0.100.3   "./entrypoint.sh --k…"   44 hours ago        Up 9 minutes                    0.0.0.0:5001->5001/tcp     testnet_raiden_1
5a035cea3c5d        exchangeunion/lnd:0.6.1-beta   "./entrypoint.sh --a…"   44 hours ago        Up 5 minutes                    0.0.0.0:10009->10009/tcp   testnet_lndbtc_1
```
It should be none or all.

**Comment by erkarl** [comment]
In the past 2 days I've experienced `lnd-ltc` and `raiden` crashes:
```
raiden_1  | matrix_client.errors.MatrixHttpLibError: Something went wrong in PUT requesting https://raidentransport.exchangeunion.com/_matrix/client/r0/presence/%400xd2e2824466479c23f413e26da5f8912c5af16bbc%3Araidentransport.exchangeunion.com/status: HTTPSConnectionPool(host='raidentransport.exchangeunion.com', port=443): Max retries exceeded with url: /_matrix/client/r0/presence/%400xd2e2824466479c23f413e26da5f8912c5af16bbc%3Araidentransport.exchangeunion.com/status?access_token=MDAyZmxvY2F0aW9uIHJhaWRlbnRyYW5zcG9ydC5leGNoYW5nZXVuaW9uLmNvbQowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwNjBjaWQgdXNlcl9pZCA9IEAweGQyZTI4MjQ0NjY0NzljMjNmNDEzZTI2ZGE1Zjg5MTJjNWFmMTZiYmM6cmFpZGVudHJhbnNwb3J0LmV4Y2hhbmdldW5pb24uY29tCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gS016Vy1kN2xZU1VASEVpVAowMDJmc2lnbmF0dXJlIO2dycMOE9Hv9RDz8wyeYbpHQJrmYpkLjgWFYduSYsmHCg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe087140190>: Failed to establish a new connection: [Errno -3] Try again'))
simnet_raiden_1 exited with code 1
```
it would definitely help a lot to have something like supervisor manage the docker processes and restart automatically.

**Comment by kilrau** [comment]
> it would definitely help a lot to have something like supervisor manage the docker processes and restart automatically.

Update: we have that by now. Restart policy not important enough, so leaving it out of `1.0.0-beta`.

**Comment by kilrau** [comment]
I am thinking if it even makes sense to have auto-restart since the environment needs to be unlocked in any case. Opinions?

**Comment by erkarl** [comment]
I think we can keep it the way it is for now.
