### ISSUE TITLE
Convert own address to be EIP55 checksummed

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#154]
Off-shoot of https://github.com/ExchangeUnion/xud/issues/1216: Own geth/raiden address should be EIP55 checksummed, otherwise raiden fails to start complaining about it.

**Comment by erkarl** [comment]
@reliveyy 
There's a script in my WIP raiden simtest branch that does this:
https://github.com/ExchangeUnion/xud/blob/feat/geth-simtest-raiden-0-31/test/simulation/address-to-eip55.sh
https://github.com/ExchangeUnion/xud/blob/feat/geth-simtest-raiden-0-31/test/simulation/utils/ethereum/eip55.py

**Comment by kilrau** [comment]
Closed in https://github.com/ExchangeUnion/xud-docker/blob/master/images/raiden/onboarder.py#L48
