### ISSUE TITLE
Do not expose RPC outside the localnet

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#156]
With the current implementation we're exposing RPC calls to the outside world. This exposes us to unnecessary security risk. We should change RPC to listen only on localnet interface so that docker containers can still communicate with each other.

**Comment by kilrau** [comment]
Translated that means there shouldn't be a single container listening to `0.0.0.0`.

**Comment by kilrau** [comment]
```
bitcoind:
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -rpcbind=0.0.0.0

  litecoind:
      -zmqpubrawblock=tcp://0.0.0.0:29332
      -zmqpubrawtx=tcp://0.0.0.0:29333
      -rpcbind=0.0.0.0

  raiden:
      --api-address 0.0.0.0:5001
```
