### ISSUE TITLE
Stuck at `Syncing: 99.99%`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#16]
┏━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  SERVICE  │  STATUS                             ┃
┠───────────┼─────────────────────────────────────┨
┃  btc      │  Syncing: 79.76% (1229699/1541725)  ┃
┠───────────┼─────────────────────────────────────┨
┃  ltc      │  Syncing: 99.99% (1106209/1106265)  ┃
┠───────────┼─────────────────────────────────────┨
┃  eth      │  Syncing: 8.45% (487064/5765146)    ┃

**Comment by reliveyy** [comment]
Some `litecoind`'s logs will be good for this issue. @kilrau

**Comment by kilrau** [comment]
Actually now it shows: `ltc      │  Syncing: 100.00% (1106218/1106265) `

which is obviously wrong, (1106218/1106265) is not 100%. Also, if it's really 100% (1106265/1106265) then it should just show `Ready`

**Comment by reliveyy** [comment]
Confirmed. It's a floating number round issue. @kilrau

**Comment by kilrau** [comment]
oh actually now it jumped to `ltc      │  OK  `. Interesting. Anyhow, the small 100.00% should be fixed and OK replaced with `Ready`. Goes for all clients including bitcoind, litecoind, geth, lnds, raiden, xud.
