### ISSUE TITLE
Get rid of python dependencies

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#179]
Currently we have `pull.py` and `xucli_create_wrapper.py`. This issue is about getting rid of these.

`pull.py` -> bash
`xucli_create_wrapper.py` -> into xud container

**Comment by reliveyy** [comment]
https://github.com/ExchangeUnion/xud-docker/pull/151 also use python instead of bash to provide long hand options support.

[Starting with macOS Catalina, your Mac uses zsh as the default login shell and interactive shell. ](https://support.apple.com/en-us/HT208050)

**Comment by kilrau** [comment]
In the meanwhile I have different thoughts on this. We'll discuss in Berlin. Closing.
