### ISSUE TITLE
Status2 - Some status field shows empty 

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#181]
Branch: `customize-homedir`

Expected behavior: showing apt service status at all times

Actual behavior: some status is left blank

PS: Removing boxes from the result because of formating issues 

testnet > status

```
SERVICE  │  STATUS  
btc      │  Ready   
lndbtc
ltc      │  Container down 
lndltc
 geth     │  Ready
raiden   │  Waiting for sync 
xud                       
```

**Comment by kilrau** [comment]
Goal should be to fix all these and replice the `status` with `status2`
