### ISSUE TITLE
1.0.0-mainnet

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#184]
- [x] update xud1.testnet.exchangeunion.com (XUD Seed) -> new node key
- [x] update xud1.exchangeunion.com (XUD Seed) -> new node key
- [x] update xud seed node keys, merge
- [x] tag release (all todo's in https://github.com/ExchangeUnion/xud/wiki/Release-Checklist)
- [x] update xud docker image, push to dockerhub
- [x] `down`, `exit`, `xud`, `2`, `y` on `xud1.testnet.exchangeunion.com` to run `1.0.0-mainnet` release tag
- [x] `down`, `exit`, `xud`, `3`, `y` `xud1.exchangeunion.com` to run `1.0.0-mainnet` release tag

**Comment by sangaman** [comment]
Release tagged, published to npm, and docker image built and pushed.

**Comment by kilrau** [comment]
I updated xud1 and xud1.testnet. Closing.
