### ISSUE TITLE
Raiden occasionally crashes because contract does not contain code

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#185]
Output:
```
raiden_1     | Error: Provided token network registry 0x04662e916bA46bf84638daF72b067478053B6801 contract does not contain code
testnet_raiden_1 exited with code 1
```

I've only managed to reproduce this twice - happens during the first start of a clean environment. I'm not sure if the issue is in our docker setup or in raiden.

Current solution is to restart raiden.

**Comment by kilrau** [comment]
Honestly, I wouldn't want to spend time on finding the root cause and just open an issue on raiden side. Let's just restart raiden if it crashes. Currently supervisord is taking care of that. Open raiden issue and close? @erkarl

**Comment by erkarl** [comment]
I've added https://github.com/ExchangeUnion/xud-docker/pull/203 to restart raiden on testnet/mainnet when this happens.
