### ISSUE TITLE
Keystore generation issues

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#186]
Keystore file gets generated successfully :tada: 

- [x] why is the keystore file placed in `.xud-docker/mainnet/data/xud/keystore` and not `.xud-docker/mainnet/data/raiden/keystore/ ? (https://github.com/ExchangeUnion/xud-docker/pull/187)
- [x] I failed to access the keystore file in a different wallet via mnemonic (e.g. https://www.myetherwallet.com/access-my-wallet). Choosing keystore file import mostly doesn't work since most other wallets require to enter a password whereas we create the keystore file without password
- [x] https://github.com/ExchangeUnion/xud/blob/master/lib/cli/commands/create.ts#L61 was not printed in my testing (https://github.com/ExchangeUnion/xud-docker/pull/189)
- [ ] XUD SEED still starts in `Re-enter password:` line from time to time:
`Re-enter password: ----------------------BEGIN XUD SEED---------------------`

I think we should answer/solve the first 3.

**Comment by kilrau** [comment]
>     * [x]  I failed to access the keystore file in a different wallet via mnemonic (e.g. https://www.myetherwallet.com/access-my-wallet). Choosing keystore file import mostly doesn't work since most other wallets require to enter a password whereas we create the keystore file without password

Since XUD Seed is an aezeed, which is somewhat specific to lnd and not supported by most ethereum wallets, one has to use `seedutil` to convert XUD seed into a functioning keystore file. @erkarl and I did some real world tests taking an XUD seed, depositing money, restoring the keystore file via XUD SEED Mnemonic & `seedutil`, importing it in MetaMask and sending funds. Worked.

**Comment by reliveyy** [comment]
I will create a PR to fix the last one after https://github.com/ExchangeUnion/xud-docker/pull/151 be merged. I'd like to use pure bash to wrap `xucli create` with the inspiration of `while read...` in https://github.com/ExchangeUnion/xud-docker/pull/191
