### ISSUE TITLE
[Y/n] prompts

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud-docker#188]
> I learned [Y/n] from ArchLinux pacman, Ubuntu apt-get and CentOS yum. They all use capitalized Y to indicate yes is the default action namely when you type Enter only you will choose yes by default. And they all accept y for yes. I think we should follow this convension.

We should make sure all prompts follow this convention. If the prompt shows a capitalized letter such as `[Y/n]`, the capitalized letter is the default action and simply pressing enter should treat it as if that letter was entered. We ignore case on the letter that was entered ('Y' 'y' 'N' 'n' are all fine).

If invalid input is detected @kilrau says the standard behavior would be to abort. I'd be fine with that, but I also think it would be reasonable to prompt the user again especially if we're in the middle of an operation.

**Comment by kilrau** [comment]
> prompt the user again especially if we're in the middle of an operation.
Prompt again is definitely better.

@reliveyy can we have one `[Y/n]` prompt module that is reused throughout docker? It always behaves exactly the same (as Daniel described above).

**Comment by kilrau** [comment]
We should have one `[Y/n]` prompt module that is reused throughout docker. It always behaves exactly as described above. Then we have a second `[y/N]` prompt, that has NO as default for more serious actions, behaving exactly the same otherwise, e.g. taking ENTER as NO.

Please compile a list where we have these right now and we decide where to use which.

**Comment by hatmer** [comment]
The yes_or_no and no_or_yes prompts are already used correctly throughout the code. I have simply improved the UX so that e.g. Yes/yes/y/Y all mean the same thing.
