### ISSUE TITLE
Tailing logs takes forever

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#215]
It takes several minutes to tail the logs via `logs -f geth/xud` after the docker environment has been running for days. Is there a way to limit the log output? Maybe we should make it default to latest 10k lines?

**Comment by kilrau** [comment]
Dependency: https://github.com/ExchangeUnion/xud-docker/issues/251 (logs -f is currently not working out of `xud ctl`.) The limit above should apply to both `docker logs -f container` and `logs -f container` from within `xud ctl`.
