### ISSUE TITLE
Reduce minimum requirements for xud-docker

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#218]
For now I can running all three networks at the same time on a 4 cores (Intel i7-7500U CPU 2.70GHz), 16G mem, 1T ssd laptop. I notice the system load average comes to the maximum value when initializing all nodes for the first time (10x than the regular value)

There are few directions for such "shrinking" optimization (NOT scaling):
1. Optimizing each container's internal logic
2. Using `runc` (OCI implementation on Linux kernel) directly, namely removing docker and docker-compose abstraction layer
3. Re-implementing all xud dependencies in one program, namely removing all dependencies nodes. (This is a very ambitious idea!)

We are not going to run every nodes without containerization because you will still need to manage the computing resources for each process in the end. That's why we are using the most popular containerization standard (OCI) at first. OCI standardize the common interfaces for managing computing resources for each process and docker/docker-compose wraps it in a more user friendly way. We are not supposed to reinvent the wheel.

**Comment by kilrau** [comment]
P3, since market makers will have the means to get a decent hardware. Not important in the next 6 months, thereafter it will be.
