### ISSUE TITLE
Text user interface for xud-docker

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#219]
This is the GUI in terminal and it can program more easily than the real GUI. Most important it gives us the possibility to create a more user-friendly interface. User can click buttons and choose options only with the mouse and they do not need to remember all the customization options in xud-docker. And it should come next to issue #216

**Comment by kilrau** [comment]
Good idea, but also P3 since market makers will be able to write config files. Especially because most is a one-time effort.

**Comment by kilrau** [comment]
Once we focus on regular traders running xud directly, I'd go for a "real" UI instead I think.

**Comment by kilrau** [comment]
I think by now we all agree, that a UI is the by far better solution.
