### ISSUE TITLE
Report "Branch ... does not exist" when meeting network failure

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#220]
This error message is misleading and should report the network failure instead.

**Comment by kilrau** [comment]
I couldn't reproduce this on current master. Error message looks fine to me:
```
kilrau@K-Yoga:~$ xud
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
🚀 Launching mainnet environment
🌍 Checking for updates ...
Failed to check for image updates. Try again? [Y/n] 
```

Closing. Please reopen if it's a different scenario you are describing @reliveyy
