### ISSUE TITLE
Geth status stuck at 99.99%

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#222]
Related to https://github.com/ExchangeUnion/xud-docker/issues/44

I had geth 100% synced on google cloud but I encounter this 99.99% problem with geth (even with full SSD support) in China mainland's network. And I have this problem for few days. It seems like geth is always ~100 blocks away from the head.

**Comment by michael1011** [comment]
geth having troubles to find reliable and fully synced peers on China's mainland might play a role in this but I have also encountered this issue in central Europe.

Check the logs from geth: if they show you something like (I don't remember the exact phrasing) `importing state entries` the fast sync is working as it should and you will catch up with the chain once geth is done processing the state.

**Comment by kilrau** [comment]
Not sure if there's much we can do here..
