### ISSUE TITLE
report.txt is too large

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#24]
In general good idea, good feature, but

```
~$ bash xud.sh report
Generate report.txt
^CERROR: Aborting.
```

Did run for several minutes and still didn't finish (report.txt in ~/.xud-docker is >100MB). Not sure how yet, but we need to filter a bit what we put in there.

**Comment by reliveyy** [comment]
Should be resolved by https://github.com/ExchangeUnion/xud-docker/pull/21 (only gather last 100 lines of log of each service)

**Comment by kilrau** [comment]
Fixed.
