### ISSUE TITLE
Integrate Backup & Restore Feature

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#245]
## 1. **Restore** (depends on https://github.com/ExchangeUnion/xud/issues/1041)

If there is already data in the xud's  <network> directory, try to start environment with that. If anything is corrupted, exit with an error.

If <network> directory is empty, ask user is she wants to create a new xud environment or restore an existing one:
```
Do you want to create a new xud environment or restore an existing one?
1. Create New
2. Restore Existing
Please choose: 
```
1 - continue as of now
2 - `Please paste the path to your xud backup files to restore your channel balance, your keys and other historical data: /glibberish`

If backup path not valid (like above) then
```
Checking files... path not available. Do you wish to continue WITHOUT restoring channel balance, keys and historical data? [Y/n] N
```
If path does not contain any files named `xud`, `raiden` `lnd-BTC` or `lnd-LTC` OR user just pressing ENTER, then:
```
Checking files... no backup files found. Do you wish to continue WITHOUT restoring channel balance, keys and historical data? [Y/n] N
```
If backup path contains files named `xud`, `lnd-BTC` and `raiden` (but e.g. not `lnd-LTC`), then:
```
Checking files... Looking good. This will restore xud, lndbtc, raiden. Do you wish to continue? [Y/n] Y
BEWARE: Restoring your environment will close your existing lnd channels and restore channel balance in your wallet. Do you wish to continue? [Y/n] y
```
Then switch to xucli restore command output:
`You are restoring an xud node key` and so on.

Next step:

## 2. **Backup** (was merged in https://github.com/ExchangeUnion/xud/pull/1032)
- CLI prompt **after showing generated SEED or after succesful Restore**:
```
Please enter a path to a destination where to store a backup of your environment. It includes everything, but NOT your wallet balance which is secured by your XUD SEED. The path should be an external drive, like a USB or network drive, which is permanently available on your device since backups are written constantly.

Enter path to backup location: /media/USB/xud-backup
Checking backup location... OK.
Checking backup location... Failed. Retry? [Y/n]  N
DOWN
```
- Backup path is persisted in `mainnet.conf` as e.g. `backup-dir = "/media/USB/xud-backup"` in a new `[backup]` section
- On every start of xud.sh, check if backup path is set and path is available and writable. If not set, ask to set as above, if not available, additionally print
```
Backup location not available.
Enter path to backup location: 
```
There is just no way the user can get into xud ctl without specifying a functioning backup path.

Like all other command line parameters, `--backup-dir` CLI parameter simply overwrites whatever is written in config file.

## Test cases

1. backup-dir missing, empty network dir (first run), choose create
- ask create or restore, user chooses create
- interactive create (password)
- ask user to enter backup-dir path (check if available, writable - see above)
- enter xudctl

2. backup-dir missing, empty network dir (first run), choose restore
- ask create or restore, user chooses restore
- interactive restore asking for mnemonic and backup file location (see above)
- ask user to enter backup-dir path (check if available, writable - see above)
- enter xudctl

3. backup-dir set, empty network dir (first run), choose create
- ask create or restore, user chooses create
- interactive create (password)
- check if backup-dir available, writable (see above)
- enter xudctl

4. backup-dir set, empty network dir (first run), choose restore
- ask create or restore, user chooses restore
- interactive restore asking for mnemonic and backup file location (see above)
- check if backup-dir available, writable (see above)
- enter xudctl

5. backup-dir set, non-empty network-dir (**not** first run)
- check if backup-dir available, writable (see above)
- if yes, try to launch environment, exit with error if anything is missing
- if no, `Checking backup location... Failed. ` & ask user to enter backup-dir path (check if available, writable - see above)

6. backup-dir not set, non-empty network-dir (**not** first run)
- ask user to enter backup-dir path (check if available, writable - see above)
- try to launch environment, exit with error if anything is missing

**Comment by erkarl** [comment]
Looks good on first glance. Some thoughts:

> prompt on every start if path not set or not available

If the path set is not available (invalid permissions, unmounted volume etc.) the script should exit.

> Please paste the path to your backup to restore your xud environment and channel balance:

By default we could get the value from the config. If the path is not available the system should also support restoring only the wallet balances.

**Comment by erkarl** [comment]
> what to do if there's already data in the default location

If existing data directory exists we could prompt user for confirmation to overwrite.

**Comment by kilrau** [comment]
Improvements of current version:
* we're updating the raiden database quite often, we should do that a bit less since the raiden db gets quite large (>150MB on our mainnet node)

**Comment by kilrau** [comment]
@sangaman @reliveyy is taking over
