### ISSUE TITLE
logs -f container_name (from within xud ctl)

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#251]
logs -f container_name

**Comment by erkarl** [comment]
Without this feature it's very cumbersome to debug the docker environment. Upping the priority.

**Comment by kilrau** [comment]
This can be done from outside with `docker logs -f mainnet_xud_1`. @reliveyy gave this a shot and it proved to be ... difficult.

**Comment by erkarl** [comment]
Fair enough - that's the workflow I've been using so far.

**Comment by reliveyy** [comment]
This feature is back in https://github.com/ExchangeUnion/xud-docker/pull/750
