### ISSUE TITLE
Change folders owned by root to current user

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#26]
Why is everything in `~/.xud-docker/testnet/data` owned by root? Current user should be sufficient.

**Comment by reliveyy** [comment]
Related to https://github.com/docker/compose/issues/3270

**Comment by kilrau** [comment]
Ok, let's keep an eye on it. `post-1.0.0` anyways.

**Comment by kilrau** [comment]
FYI: I just chowned everything in `~/.xud-docker/` to my current user and things are still working, so this must be possible.

**Comment by kilrau** [comment]
UX problem: config files are owned by root and need root privileges to be modified

Why are folders owned by root: folders are created by docker, which defaults the folder owner to root. A script chowning folders to current user would need to be run with root privileges and is kinda hacky. 

Is there any way, that docker can create these folders with owner current user? @reliveyy

**Comment by kilrau** [comment]
Duplicate of https://github.com/ExchangeUnion/xud-docker/issues/249.
