### ISSUE TITLE
Allow multiple utils containers

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#260]
If one has xud ctl open elsewhere, the utils container exists (because it holds the shell), or if xud ctl was not exited in a clean way, the utils container might still be up too. This leads to a container name collision error and one cannot get into `xud ctl` anymore unless the utils container is manually stopped via `docker stop`. Happened quite often to me and it's annoying.

How it should be: tell the user that there is still another (or multiple) `xud ctl` session open and ask if the user wants to close existing xud ctl sessions. If yes, docker stop *all* open utils containers and start *one* fresh utils container. If no, open a second, third appending `_2`, `_3` etc. utils container

```
xud@ubuntu:~$ bash ~/xud.sh
1) Simnet
2) Testnet
3) Mainnet
Please choose the network: 3
🚀 Launching mainnet environment
🌍 Checking for updates...
All up-to-date.
Found 2 existing xud ctl sessions. Do you want to close these? [Y/n] Y
Stopping mainnet_utils_1
Stopping mainnet_utils_2
Removing mainnet_utils_1
Removing mainnet_utils_2
Starting mainnet_utils_1
```

**Comment by erkarl** [comment]
I can confirm that this restriction is really annoying when one tries to monitor the environment with multiple `xud.sh` instances running.
