### ISSUE TITLE
bitcoind/litecoind with `disable-wallet`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#262]
If arm64 succeeded (https://github.com/ExchangeUnion/xud-docker/pull/259#issuecomment-573801037), let's do this for amd64 images too.

**Comment by kilrau** [comment]
arm64 works fine, so let's do this for amd64 too

**Comment by reliveyy** [comment]
The `--disable-wallet` option is already within the master images. Close the issue.

https://github.com/ExchangeUnion/xud-docker/blob/3561fadbaf06a6ca9b835d1f7255b429f2885f95/images/bitcoind/0.19.0.1/Dockerfile#L9
https://github.com/ExchangeUnion/xud-docker/blob/3561fadbaf06a6ca9b835d1f7255b429f2885f95/images/litecoind/0.17.1/Dockerfile#L13
