### ISSUE TITLE
configuration file issues

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#263]
- [x] `sample-xud-docker.conf` is not being created in (~/.xud-docker)
- [x] look for existing .conf file on first start and read in if it exists. To state the obvious: Even if config file exists, doesn't mean environment exists (our nodekey.dat detection stays). Goal: make https://docs.exchangeunion.com/start-earning/market-maker-guide#preparation-light-setup work
- [ ] `<network>.conf` & `sample-<network>.conf` are both being created. How it should be: only `sample-<network>.conf` is created containing the latest config options (and is updated regularly). User is using  `cp `sample-mainnet.conf mainnet.conf` to create his own copy and modify. For all 3 networks. 
- [x] update docs with `cp `sample-<network>.conf` instructions (@kilrau )

**Comment by kilrau** [comment]
@peartobear just ran into that when following https://docs.exchangeunion.com/start-earning/market-maker-guide#preparation-light-setup where the setup wrote duplicate values into `testnet.conf` and that caused the start to fail. Let's fix that asap since it breaks things! @reliveyy

**Comment by reliveyy** [comment]
> look for existing .conf file on first start and read in if it exists. To state the obvious: Even if config file exists, doesn't mean environment exists (our nodekey.dat detection stays). Goal: make https://docs.exchangeunion.com/start-earning/market-maker-guide#preparation-light-setup work

Does this issue still exists? I didn't any blocker in the guide `preparation-light-setup`. @kilrau

**Comment by kilrau** [comment]
Nope, that works fine. Marked it as done.
