### ISSUE TITLE
Expose ports without rebuilding utils image

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#282]
**Is your feature request related to a problem? Please describe.**
Currently we need to build a new utils image to expose some other ports. It's not convenient for developers.

**Describe the solution you'd like**
I sugguest adding option `--expose-ports` in xud.sh. The syntax could be

```
--expose-ports geth/8545
--expose-ports geth/8545,bitcoind/8832
--expose-ports geth/192.168.1.100:8545:8545
--expose-ports geth/8545/tcp
```

The value of `--expose-ports` is comma separated and every part follows `<node>/<published-port>` which `published-port` follows the same pattern as [docker `-p` option](https://docs.docker.com/config/containers/container-networking/#published-ports)

**Describe alternatives you've considered**
I think add options in &lt;network&gt;.conf is not good. I sugguest all options for developers should be limited in xud.sh command line options.

**Additional context**
None.

**Comment by erkarl** [comment]
This is necessary for arby<->xud-docker integration down the road.

**Comment by erkarl** [comment]
As a workaround I'm currently using a separate branch with a custom utils image that exposes the gRPC port of xud.

**Comment by kilrau** [comment]
Since it is quite some work for @erkarl  to constantly rebase the `expose-xud-grpc` branch, upping prio here. Also it is highly desirable to be able to easily expose other ports too. Here the desired ports one should be able to open (`EXPOSE` on host system) via entry in `<network>.conf` (should become active once restarting the environment). To be added in

### sample-mainnet.conf
```
[bitcoind]
#expose-port-8332 = true
#expose-port-8333 = true
#expose-port-28332 = true
#expose-port-28333 = true

[litecoind]
#expose-port-9332 = true
#expose-port-9333 = true
#expose-port-29332 = true
#expose-port-29333 = true

[geth]
#expose-port-8545 = true
#expose-port-30303 = true

[lndbtc]
#expose-port-9735 = true
#expose-port-10009 = true

[lndltc]
#expose-port-10735 = true
#expose-port-20010 = true

[raiden]
#expose-port-5001 = true

[xud]
#expose-port-8885 = true
#expose-port-8886 = true
#expose-port-8887 = true
#expose-port-8080 = true
#expose-port-9050 = true
```

### sample-testnet.conf
```
[bitcoind]
#expose-port-18332 = true
#expose-port-18333 = true
#expose-port-38332 = true
#expose-port-38333 = true

[litecoind]
#expose-port-19332 = true
#expose-port-19333 = true
#expose-port-39332 = true
#expose-port-39333 = true

[geth]
#expose-port-18545 = true
#expose-port-40303 = true

[lndbtc]
#expose-port-19735 = true
#expose-port-20009 = true

[lndltc]
#expose-port-20735 = true
#expose-port-20010 = true

[raiden]
#expose-port-15001 = true

[xud]
#expose-port-18885 = true
#expose-port-18886 = true
#expose-port-18887 = true
#expose-port-18080 = true
#expose-port-19050 = true
```

**Comment by kilrau** [comment]
Could you sanity check the ports? @erkarl @sangaman

**Comment by erkarl** [comment]
Maybe it makes sense to expose an array of ports for a given container? For example:
```
[xud]
expose = ["18885", "8886"]
```

**Comment by kilrau** [comment]
Makes sense. And the ports itself?

We should have good defaults, so user "just needs to uncomment".

**Comment by reliveyy** [comment]
> We should have good defaults, so user "just needs to uncomment".

I agree that it's hard to remember the specific port numbers for users. And it's convenient to turn on a port exposure by just uncommenting one line. But the syntax of the configuration file is not that good.

My viewpoint about the balance between convenience and better syntax is that we should keep [best practice](https://github.com/toml-lang/toml#example) of TOML syntax since we are using it for our configuration files. And for such "one-click" user experience it's better to have a GUI/TUI for it. For instance, when you compiling Linux kernel you can modify the config file manually or use "menuconfig" which is a TUI to set right configuration by just few clicks. 

And for the port numbers, I suggest to adding descriptive comments for each ports above the option.

```toml
[bitcoind]
# 8332 - bitcoind mainnet JSON-RPC port
# 18332 - bitcoind testnet JSON-RPC port
# 28332 - bitcoind ZeroMQ raw blocks publication port (zmqpubrawblock)
# 28333 - bitcoind ZeroMQ raw transactions publication port (zmqpubrawtx)
expose-ports = [8332, 18332, 28332, 28333]
```

**Comment by kilrau** [comment]
Thanks for your suggestions! Combining these, I compiled the following `<network>` specific additions for the config files:

### sample-mainnet.conf
```
[bitcoind]
# 8332 - JSON-RPC port
# 8333 - P2P port
# 28332 - ZeroMQ raw blocks publication port (zmqpubrawblock)
# 28333 - ZeroMQ raw transactions publication port (zmqpubrawtx)
#expose-ports = [8332,8333,28332,28333]

[litecoind]
# 9332 - JSON-RPC port
# 9333 - P2P port
# 29332 - ZeroMQ raw blocks publication port (zmqpubrawblock)
# 29333 - ZeroMQ raw transactions publication port (zmqpubrawtx)
#expose-ports = [9332,9333,29332,29333]

[geth]
# 8545 - HTTP-RPC port
# 30303 - P2P port
#expose-ports = [8545,30303]

[lndbtc]
# 9735 - P2P port
# 10009 - gRPC port
# 10010 - REST port 
#expose-ports = [9735,10009,10010]

[lndltc]
# 10735 - P2P port
# 11009 - gRPC port
# 11010 - REST port 
#expose-ports = [10735,20009,20010]

[raiden]
# 5001 - raiden API port
#expose-ports = [5001]

[xud]
# 8885 - P2P port
# 8886 - gRPC port
# 8887- raiden resolver port
# 8080 - webproxy port
#expose-ports = [8885,8886,8887,8080]
```

### sample-testnet.conf
```
[bitcoind]
# 18332 - JSON-RPC port
# 18333 - P2P port
# 38332 - ZeroMQ raw blocks publication port (zmqpubrawblock)
# 38333 - ZeroMQ raw transactions publication port (zmqpubrawtx)
#expose-ports = [18332,18333,38332,38333]

[litecoind]
# 19332 - JSON-RPC port
# 19333 - P2P port
# 39332 - ZeroMQ raw blocks publication port (zmqpubrawblock)
# 39333 - ZeroMQ raw transactions publication port (zmqpubrawtx)
#expose-ports = [19332,19333,39332,39333]

[geth]
# 18545 - HTTP-RPC port
# 40303 - P2P port
#expose-ports = [18545,40303]

[lndbtc]
# 19735 - P2P port
# 20009 - gRPC port
# 20010 - REST port 
#expose-ports = [19735,20009,20010]

[lndltc]
# 20735 - P2P port
# 21009 - gRPC port
# 21010 - REST port 
#expose-ports = [20735,21009,21010]

[raiden]
# 15001 - raiden API port
#expose-ports = [15001]

[xud]
# 18885 - P2P port
# 18886 - gRPC port
# 18887- raiden resolver port
# 18080 - webproxy port
#expose-ports = [18885,18886,18887,18080]
```

PS: I took out xud port 9050 (tor) since I don't see why one would want to expose that. Wdyt? @erkarl 

Final sanity check please if above is all correct. I wouldn't mind never touching port exposures again. @erkarl @sangaman

**Comment by reliveyy** [comment]
Reopen this issue for further ports discussion.

**Comment by kilrau** [comment]
What exactly is the discussion about? What is missing?

**Comment by sangaman** [comment]
I'm not sure what's remaining either. Might make sense to have it in a separate issue anyhow?

**Comment by reliveyy** [comment]
Expected sample-mainnet.conf in this issue
```
[bitcoind]
#expose-ports = [8332,8333,28332,28333]
[litecoind]
#expose-ports = [9332,9333,29332,29333]
[geth]
#expose-ports = [8545,30303]
[lndbtc]
#expose-ports = [9735,10009,10010]
[lndltc]
#expose-ports = [10735,11009,11010]
[raiden]
#expose-ports = [5001]
[xud]
#expose-ports = [8885,8886,8887,8080]
```

Real sample-mainnet.conf on master

```
[bitcoind]
#expose-ports = ["8332", "8333", "28332", "28333"]
[litecoind]
#expose-ports = ["9332", "9333", "29332:28332", "29333:28333"]
[geth]
#expose-ports = ["8545", "30303/udp"]
[lndbtc]
#expose-ports = ["9735", "10009", "10010"]
[lndltc]
#expose-ports = ["10735", "20009:10009", "20010:10010"]
[raiden]
#expose-ports = ["5001"]
[xud]
#expose-ports = ["8885", "8886", "8887"]
```

You cloud see differences between these two. And it is same to testnet and simnet. That's the unresolved part of this issue I mean.

**Comment by kilrau** [comment]
Got it, hard to do?

PS: fixed a typo in the lndltc ports in your post above (11009/110010 now).

**Comment by reliveyy** [comment]
> hard to do?

It is not difficult to implement. But it will introduce a lot of cumbersome code.

We use different ports when we run multiple processes on the same host. However in this project process are running inside containers. Each process has their own host. This is an advantange Docker brings to us that we should utilize.

I accept that we use different P2P ports for different networks becuase it's straightforward to tell the network from the port number. But for other ports I think we use them mostly when debugging. And we already got ports exposure feature and port re-mapping enhancement. So I didn't set huge requirements to change others ports to some unique value at the moment.

**Comment by kilrau** [comment]
> It is not difficult to implement. But it will introduce a lot of cumbersome code.

Ok, moved to separate, low prio issue: https://github.com/ExchangeUnion/xud-docker/issues/362

> But for other ports I think we use them mostly when debugging. And we already got ports exposure feature and port re-mapping enhancement. So I didn't see huge requirements to change other ports to some unique value at the moment.

I disagree. When we offer to expose ports there simply can never ever be a port collission on the host. And it's very easy to do: just create the mappings for the host ports exactly as in https://github.com/ExchangeUnion/xud-docker/issues/282#issuecomment-598378806. Please do that, then we can close this issue @reliveyy

**Comment by kilrau** [comment]
Opened separate issues. Closing here.
