### ISSUE TITLE
xud commands take a long time to become responsive (aka "rm proxychains")

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#283]
**Describe the bug**
xud commands (gRPC) take a long time to become responsive when starting the environment.

**To Reproduce**
1. Use an existing testnet/mainnet node that has many nodes/peers in the database
2. Start the environment
3. Unlock xud
4. ERROR: `getinfo` takes several minutes to respond (in my case 15m+)

**Expected behavior**
Getinfo should always be responsive when xud is unlocked.

**Additional context**
In the logs it shows that it's trying to connect to many outbound peers when unlocked. I suspect our tor integration is causing the thread to block.

**Comment by erkarl** [comment]
Confirming that this is caused by `proxychains` blocking our thread. Without it our gRPC becomes responsive immediately.

**Comment by kilrau** [comment]
Now that https://github.com/ExchangeUnion/xud/pull/1395#event-3053293084 is merged, we can continue here.

**Comment by kilrau** [comment]
closed by https://github.com/ExchangeUnion/xud-docker/pull/303
