### ISSUE TITLE
Mainnet | Environment shutting down as error is showing "13 INTERNAL: could not generate aezeed"

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#285]
**Describe the bug**
Mainnet | Environment shutting down as error is showing "13 INTERNAL: could not generate aezeed"

**To Reproduce**
1. Launch AWS instance (C4.2xlarge, 16GB RAM, 200 GB SSD, 8 vCPU, Ubuntu 18.04)
2. Run through basic setup based on https://docs.exchangeunion.com/start-earning/market-maker-guide
3. Launch Mainnet by selecting option 3
4. Validate the error

**Expected behavior**
Mainnet environment should be up and running successfully

**Actual behaviour**
It shows an error "13 INTERNAL: could not generate aezeed" and hence environment launch is failing

**Screenshots**

https://www.dropbox.com/home/ExchangeUnion_Testing_11282019?preview=Testnet_Mainnet_20191128.mov

[xud-docker_mainnet.log](https://github.com/ExchangeUnion/xud-docker/files/4139114/xud-docker_mainnet.log)

**Comment by kilrau** [comment]
This is outdated and working now.
