### ISSUE TITLE
Don't create empty <network> dir

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#294]
**Describe the bug**
If I set `simnet-dir`, `testnet-dir` and/or `mainnet-dir` to a different location in `xud-docker.conf`, the setup still creates an (empty) `simnet`, `testnet`, `mainnet` directory in `~/.xud-docker` (the default location) on every `bash xud.sh`.

**Expected behavior**
It does not create these empty folders.

**Comment by reliveyy** [comment]
I cannot reproduce this issue on the latest master. @raladev Could you confirm on that quickly?

**Comment by raladev** [comment]
Not reproduced for current master.
Only specified folder was created.
Closed
