### ISSUE TITLE
Find and implement an alternative to coreutils on macOS

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#296]
the docker image exits with `/dev/fd/63: line 105: realpath: command not found` on macOS, find an alternative to the realpath GNU command so that it works out of the box on MacOS

**Comment by reliveyy** [comment]
I prefer to use this function to replace `realpath` on macOS.

```bash
function normalize_path()
{
    # Remove all /./ sequences.
    local   path=${1//\/.\//\/}
    
    # Remove dir/.. sequences.
    while [[ $path =~ ([^/][^/]*/\.\./) ]]
    do
        path=${path/${BASH_REMATCH[0]}/}
    done
    echo $path
}
```

Ref.
1. [Normalizing Path Names with Bash](https://www.linuxjournal.com/content/normalizing-path-names-bash)
2. [Bash script absolute path with OS X](https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x)

**Comment by kilrau** [comment]
LGTM

**Comment by kilrau** [comment]
Since we want `beta.3` to work on macOS too. Can we do this? @reliveyy

**Comment by reliveyy** [comment]
Yes. @kilrau

**Comment by reliveyy** [comment]
I found `realpath` usage is gone since we map `/` to `/mnt/hostfs` in utils container.

**Comment by kilrau** [comment]
@peartobear please also quickly spin up a fresh light setup on your mac to confirm all is working out smoothly

**Comment by peartobear** [comment]
It is not working for me on Mac

![Screenshot 2020-04-14 at 8 24 04 PM](https://user-images.githubusercontent.com/44926540/79239335-15895900-7e8e-11ea-9168-d021de0d30ef.png)

**Comment by kilrau** [comment]
I don't think it's related to this issue since it's this `xud is running and unlocked` message that signifies that something is wrong. You try a bit more, watch logs and try to find out why it's caught in this loop?

I just tested a fresh light setup on testnet and it works for me.

**Comment by reliveyy** [comment]
> It is not working for me on Mac

I saw the error "xud is running and unlocked". I think it's becuase the wrong `noencrypt` option value in xud.conf. Please reference https://github.com/ExchangeUnion/xud-docker/pull/395#issuecomment-613242009
