### ISSUE TITLE
Avoid xud container restart for backup path injection

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#298]
In order to make https://github.com/ExchangeUnion/xud-docker/pull/287 work, we are currently restarting the xud container once to map the entered backup path into the container. Invisible xud restarts have to be avoided since this can cancel open orders, thus we need to find a way to inject the backup path into the xud container without restarting xud

**Comment by reliveyy** [comment]
Since this commit https://github.com/ExchangeUnion/xud-docker/pull/287/commits/3bd125930c26372f6e6b14e6fbe21fa2c84ebb95, this issue is no longer valid.
