### ISSUE TITLE
Build images in Travis

### ISSUE THREAD

**Issue by michael1011** [ExchangeUnion/xud-docker#300]
Related to #132 

Right now images have to pushed manually when a PR should be tested or is merged. Which is not only a chore to do but also not that easy when you don't have some kind of ARM64 emulator set up.

I propose that we setup a [Travis build on multiple CPU architectures (AMD64 and ARM64 should be enough for us)](https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures). Travis allows to store encrypted secrets for the login credentials of Docker Hub and even has nice [docs](https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry) for pushing to Docker hub.

**Comment by kilrau** [comment]
Simnet -> latest xud master
Testnet -> latest xud master
Mainnet -> latest xud release
