### ISSUE TITLE
Progressive launching

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#305]
**Is your feature request related to a problem? Please describe.**
There are dependencies between components of xud-docker. But our current launching strategy ignores these dependencies. So some edge cases are enlarged in such strategy like [this comment](https://github.com/ExchangeUnion/xud-docker/pull/299#issuecomment-589769190) described.

> I think the reality is that lnd/bitcoind/litecoind all take some time to get to a "ready" state and that spinning up everything all at once as we do with xud-docker requires some patience. I'm not exactly sure on the best/nicest way to let users know that, perhaps a waiting screen or just clearer messages that the environment is still starting up when calls fail immediately after unlock.

The dependecies:
* Xud depends on raiden and lnds
* Lnd dependes on bitcoind/litecoind/neutrino
* Raiden dependes on geth/infura

**Describe the solution you'd like**
I'd like to introducing a progressive launching strategy. In this strategy we define all prerequisites for each component and xud-docker will make sure all prerequisites are met before actually starting each component. So we will introducing a "hold on" status for each component.

What needs to be implemented?
- A "supervisor" daemon of the whole xud-docker environment. It's need to be running while the xudctl shell is running. This daemon controls the actual progressive launching progress.
- The "ensure_containers"("start_containers" before) function inside utils will be asynchronized

After this feature, xud could assume raiden and lnds are ready to use before starting; and so does lnd and raiden. But this feature cannot avoid the edge case that the dependencies are broken after the component entering the ready state and it does NOT handle its dependency break properly. So in order to solve this case, I'd like to introducing a xud-docker __context querying API__, that means each components are whole environment awareness, more specifically, this API provide a chance to check dependencies' dependency broken. 

For instance, while bitcoind is validating blocks but lnd doesn't handle this case properly so xud could using this API to know bitcoind is validating blocks and do some advanced operations that could not be done without knowing more information about layer 1 nodes. This is the worst case because xud breaks the layer responsibility segregation and it will make the system become more complicated. A better solution for bitcoind validating is that we add bitcoind ready as prerequisite for lnd. So lnd won't be ready if bitcoind is still validating blocks (not ready).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kilrau** [comment]
Not a small feat. What is your take? @engwarrior 

Concept first.

**Comment by kilrau** [comment]
So far we made things work without this feature. I am closing this until we see a need for it again in future.
