### ISSUE TITLE
tools/build multiple versions for xud

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#306]
**Is your feature request related to a problem? Please describe.**
Currently the testnet and simnet using xud latest but mainnet using 1.0.0-beta. However the versions.ini is limited to only one version. So building another version need to manully change versions.ini then build that version. But the image with another version will have a broken label "com.exchangeunion.image.revision"  
which has a "-dirty" suffix.

**Describe the solution you'd like**

Change original versions.ini syntax from

```
[application]
bitcoind = 0.19.0.1
litecoind = 0.17.1
lnd = lightningnetwork/lnd:v0.8.2-beta
geth = v1.9.10
raiden = ExchangeUnion/raiden:develop
xud = ExchangeUnion/xud:v1.0.0-beta

[tag]
bitcoind = 0.19.0.1
litecoind = 0.17.1
lnd = 0.8.2-beta
geth = 1.9.10
raiden = latest
xud = 1.0.0-beta
```

to

```
[node.bitcoind]
0.19.0.1 = 0.19.0.1

[node.litecoind]
0.17.1 = 0.17.1

[node.lnd]
0.8.2-beta = lightningnetwork/lnd:v0.8.2-beta

[node.geth]
1.9.10 = v1.9.10

[node.raiden]
latest = ExchangeUnion/raiden:develop

[node.xud]
latest = ExchangeUnion/xud:master
1.0.0-beta = ExchangeUnion/xud:v1.0.0-beta
```

or more specific style (It's hard to express list beautifully in ini or toml file. So I choose to use json. It's natively supported by Python like ini)

```json
{
  "base":{
    "alpine":"3.10",
    "golang":"1.12-alpine3.10",
    "python":"3.7-alpine3.10",
    "node":"12-alpine3.10"
  },
  "node":{
    "bitcoind":{
      "0.19.0.1":{
        "VERSION":"0.19.0.1"
      }
    },
    "litecoind":{
      "0.17.1":{
        "VERSION":"0.17.1"
      }
    },
    "lnd":{
      "0.8.2-beta":{
        "REPO":"lightningnetwork/lnd",
        "BRANCH":"v0.8.2-beta"
      }
    },
    "geth":{
      "1.9.10":{
        "VERSION":"v1.9.10"
      }
    },
    "raiden":{
      "latest":{
        "REPO":"ExchangeUnion/raiden",
        "BRANCH":"develop"
      }
    },
    "xud":{
      "latest":{
        "REPO":"ExchangeUnion/xud",
        "BRANCH":"master"
      },
      "1.0.0-beta":{
        "REPO":"ExchangeUnion/xud",
        "BRANCH":"1.0.0-beta"
      }
    }
  }
}
```

**Describe alternatives you've considered**
Change images folder structure like most docker projects:

images
- bitcoind
  - 0.19.0.1
- litecoind
  - 0.17.1
- lnd
  - 0.8.2-beta
- geth
  - 1.9.10
- raiden
  - latest
- xud
  - latest
  - 1.0.0-beta

This approach have advantages on integrating with dockerhub build or other CI build maybe. But it will also need to copy files over different tag folders.

**Additional context**
N/A

**Comment by kilrau** [comment]
To be fixed (discovered by @erkarl ):
`testnet is using exchangeunion/xud:latest when in versions.ini it's set toxud = 1.0.0-beta`

**Comment by kilrau** [comment]
What we want:

Simnet -> latest xud master, latest L1+L2 client versions
Testnet -> latest xud master,  latest L1+L2 client versions
Mainnet -> latest xud **release**, fixed L1+L2 client versions (might be different from Simnet/Testnet)

**Comment by kilrau** [comment]
More detailed proposal on how docker tags should look like (https://github.com/ExchangeUnion/xud-docker/blob/master/images/versions.ini needs to be adjusted to support this):

# Mainnet
bitcoind: `0.19.0.1`
litecoind: `0.17.1`
geth: `1.9.11`
lnd: `0.9.0`
raiden: `0.100.5a1.dev162-2217bcb`
xud: `v1.0.0-beta.1`
utils: `20.02.27`

# Testnet all docker tags are "lates", we decide what to push inside
bitcoind: `latest` (e.g. 0.19.1RC2)
litecoind: `latest` (e.g. 0.17.1)
geth: `latest` (e.g. 1.9.11)
lnd: `latest` (e.g. 0.9.1.RC1)
raiden: `latest` (0.100.5a1.dev162-2217bcb)
xud: `latest` (master)
utils: `latest` (master)

# Simnet
ltcd: `latest` (e.g. v0.20.1-beta)
lnd: `latest` (e.g. 0.9.1.RC1)
raiden: `latest` (0.100.5a1.dev162-2217bcb)
xud: `latest` (master)
utils: `latest` (master)

I propose to start tagging independent xud-docker releases in the for `yy.mm.dd` every time anything in the mainnet bundle changes, e.g. updating lnd to the latest release.
