### ISSUE TITLE
TestNet & MainNet | Unable to unlock wallet

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#307]
**Describe the bug**
After setting up the docker environment, not able to unlock the wallet for testnet as it throws an error - "Error: 12 UNIMPLEMENTED: call is not supported by the current state of xud"

**To Reproduce**
Steps to reproduce:

1. Launch AWS EC2 instance
2. Download xud.sh script following Installation steps
3. Run "bash xud.sh" & select testnet option
4. Run fresh installation along with password setup
5. Run "Unlock"
6. Enter the password which is configured on step 4
7. Validate error
8. Repeat steps 3 to 6 after executing the command - "docker system prune -a"
9. Repeat steps 1 to 8 for Mainnet

**Expected behavior**
Wallet should be unlocked

**Actual behavior**
It throws an error. "Error: 12 UNIMPLEMENTED: call is not supported by the current state of xud"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[testnet.log](https://github.com/ExchangeUnion/xud-docker/files/4244241/testnet.log)

[mainnet.log](https://github.com/ExchangeUnion/xud-docker/files/4244251/mainnet.log)

**Comment by kilrau** [comment]
Could you test this again
- with the latest release in your existing env
- with the latest relase in a fresh environment 

@fagunbhavsar

**Comment by fagunbhavsar** [comment]
@kilrau @sangaman - In both ways, it's working fine. We can close this. Thanks
