### ISSUE TITLE
Replace all infinite loops with timeout and retries

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#308]
**Is your feature request related to a problem? Please describe.**
There is [one case](https://github.com/ExchangeUnion/xud-docker/pull/303#issuecomment-590836267) which lncli getinfo failed and retry again and again. It turns out the xud script stucking there and not responding. I think this is not a good user experience.

```
2020-02-25 12:11:09.701 DEBUG 1 --- [MainThread] launcher.node.lndbtc: lncli -n testnet -c bitcoin getinfo (exit_code=1)
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
```

**Describe the solution you'd like**
Replace the infinite loop with a timeout and interactive retries. So the user will not have this strange stucking experience.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kilrau** [comment]
Also: let's set timeouts to something like 30s, e.g. timeouts of status command to fet status from clients seems to be several minutes which is way too long.

**Comment by kilrau** [comment]
fetching... for xud is running for several minutes before timing out.
```
simnet > status
┌─────────┬──────────────────────────────────────────────────┐
│ SERVICE │ STATUS                                           │
├─────────┼──────────────────────────────────────────────────┤
│ lndbtc  │ Ready 100.00% (30960/30960)                      │
├─────────┼──────────────────────────────────────────────────┤
│ lndltc  │ Ready 100.00% (31038/31038)                      │
├─────────┼──────────────────────────────────────────────────┤
│ connext │ Ready                                            │
├─────────┼──────────────────────────────────────────────────┤
│ xud     │ fetching..                                       │
└─────────┴──────────────────────────────────────────────────┘
```

**Comment by kilrau** [comment]
Especially https://github.com/ExchangeUnion/xud-docker/issues/308#issuecomment-621732168 is quite annoying in everyday operations. Would you want to give this a shot? @hatmer

**Comment by kilrau** [comment]
Fetching is still running several **minutes** before timing out and can't be CTRL+C'ed:
![image](https://user-images.githubusercontent.com/19181985/84500267-78dc0f80-acb4-11ea-96c7-8bbb03ef50dc.png)

**Comment by kilrau** [comment]
Additionaly I'd want to check why `fetching...` is failing to fetch status's because once the CLI returned and I run e.g. `bitcoin-cli getblockchaininfo` I get a response in 2-3 seconds.
