### ISSUE TITLE
TestNet | Not able to connect to the given node as it shows "Tor is disabled"

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#310]
**Describe the bug**
On Testnet, unable to connect to the given node

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Amazon EC2 instance
2. Run fresh installation after "docker system prune -a"
3. Select option 2 - testnet
4. Complete installation by entering backup details and password for wallet
5. Unlock wallet by entering password
6. Run connect node
7. Validate result

**Expected behaviour**
From localmachine, the given node should be connected

**Actual behaviour**
It throws an error; showing Tor is disabled

![Screenshot 2020-02-25 at 4 20 21 PM](https://user-images.githubusercontent.com/18718151/75259553-36c6b500-580e-11ea-9201-0306e6867feb.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by erkarl** [comment]
Is tor enabled in the config?

**Comment by kilrau** [comment]
I assume this is current xud-docker master branch (`bash xud.sh` without specifying `-b`)?

**Comment by fagunbhavsar** [comment]
@kilrau No. Sorry as I forgot to mention - this is on branch feat/restore

**Comment by erkarl** [comment]
This is fixed in master branch.

xud now requires `tor = true` and `torpor = 9050` in order to allow outbound tor connections.

**Comment by kilrau** [comment]
Could you test this again

    with the latest release in your existing env
    with the latest relase in a fresh environment

@fagunbhavsar

**Comment by erkarl** [comment]
With an existing env one needs to update `data/xud/xud.conf` with:
https://github.com/ExchangeUnion/xud/blob/master/sample-xud.conf#L73-L74

Tor port in xud container is 9050.

**Comment by fagunbhavsar** [comment]
@erkarl @kilrau In both ways, it's working fine. We can close this. Thanks
