### ISSUE TITLE
TestNet | Getnodeinfo throwing an error "<node_id> is unknown

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#311]
**Describe the bug**
On TestNet, GetNodeInfo command is showing an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Amazon EC2 instance
2. Run fresh installation after "docker system prune -a"
3. Select option 2 - testnet
4. Complete installation by entering backup details and password for wallet
5. Unlock wallet by entering password
6. Run getnodeinfo by passing the given node id
7. Validate result

**Expected behaviour**
It should show correct node information

**Actual behaviour**
It throws an error; showing node is unknown

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![Screenshot 2020-02-25 at 4 19 59 PM](https://user-images.githubusercontent.com/18718151/75259940-d2582580-580e-11ea-9403-272b9aff4c5f.png)

**Comment by kilrau** [comment]
Ehm, are you sure you are connected to these nodes (`listpeers`)? You can only `getnodinfo` of peers you are connected to.

**Comment by fagunbhavsar** [comment]
@kilrau Well, i guess then - this is a related issue to #310 as I am unable to connect at first place

**Comment by fagunbhavsar** [comment]
@kilrau Well, i guess then - this is a related issue to #310 as I am unable to connect at first place

**Comment by kilrau** [comment]
Meaning `listpeers` is empty?

**Comment by fagunbhavsar** [comment]
@kilrau Nopes, listpeers were showing values both local and remote node. I have the log, should I attach here?

**Comment by kilrau** [comment]
Just the output of `xucli listpeers` suffices.

**Comment by fagunbhavsar** [comment]
![Screenshot 2020-02-26 at 6 40 43 PM](https://user-images.githubusercontent.com/18718151/75382521-a321e100-5900-11ea-83f7-d2a0f2116384.png)

**Comment by kilrau** [comment]
This shows that your are not connected to any of the nodes that you are trying to `getnodeinfo` from. This is expected behavior. Closing.
