### ISSUE TITLE
Chore: Utils folder should be handled gracefully when installation is half-done/resumed

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#312]
Right now, if an installation for Testnet or Mainnet is stuck and when it is tried to rerun - it shows an error /mainnet_utils or /testnet_utils is already used by a container. And user has to delete is manually.

This is should be taken care by logic to make the process smooth.

cc: @reliveyy

**Comment by kilrau** [comment]
Thanks for htis issue, I agree it needs to be fixed urgently.

But a duplicate: https://github.com/ExchangeUnion/xud-docker/issues/260. Any details in there please, closing here.
