### ISSUE TITLE
Order of Mnemonics | If an order of mnemonics is changed, it does not take installation further however it shows misleading error

### ISSUE THREAD

**Issue by fagunbhavsar** [ExchangeUnion/xud-docker#321]
**Describe the bug**
Right now, if a user copy-pastes those 24 Mnemonics in any random order/reverse order; although it does not take installation further but showing misleading error. 

**To Reproduce**
1. Connect to AWS EC2 instance
2. Start installation from scratch (after deleting with docker system prune -a)
3. Selection testnet 
4. Select restore option
5. Change the order of 24 Mnemonics while pasting (reverse the order or make it random)
6. Validate next step 

**Expected behavior**
There should be a relevant error showed up at step 6

**Actual behaviour**
Right now step 6 - it asks for password setup; once user enters and reenters password; it shows an error - Error 2 UNKNOWN: Command failed

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot 2020-03-04 at 1 24 26 PM](https://user-images.githubusercontent.com/18718151/75859233-a268dd80-5e1f-11ea-9e42-ee8245125e5d.png)

**Comment by kilrau** [comment]
Should we add `Did you enter the words in the correct order?` to the error message? @sangaman
