### ISSUE TITLE
Moving Tor to a central container (one Tor for all)

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#331]
**Is your feature request related to a problem? Please describe.**
The general idea is to make our Docker images smaller and let the user download new images less frequently.

* supervisor ~ 44MB
* bash ~ 2MB
* tor ~ 11MB

Currently we leave some configuration inside the image. It will let the user download a new image
when some part of the configuration changed. And it makes our image less reusable. We used to do this (embeding configuration into images) becuase we are using docker-compose and it is lake of programatically control over the containers. But it is different now.

And moving Tor to an individual container will make our images conform the recommended [*"one process per container"*](https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container) pattern.

**Describe the solution you'd like**
The ideal images should only include binary and cli for each node. And moving configuration out of the image will make the image more reusable.

And for the Tor part, I found Tor has [a control protocol](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt) which can be used to dynamically add or remove "HiddenService"s (a Tor-style public network ports exposure) 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kilrau** [comment]
I share the opinion with @erkarl "one tor container per network". Reason is increased privacy and that we potentially have experimental tor container releases for testnet, whereas mainnet stays on a stable release version.
