### ISSUE TITLE
Expose every config file option to a command-line option

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#344]
**Is your feature request related to a problem? Please describe.**
Provide a more unified user experience. This feature request is originate from https://github.com/ExchangeUnion/xud-docker/pull/343#issuecomment-600992325.

**Describe the solution you'd like**
It follows the pattern `--<node>.<option>`. This is going to change `--expose-ports geth/8545` to `--geth.expose-ports=8545` and `--bitcoind-neutrino` to `--bitcoind.mode=neutrino".

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kilrau** [comment]
Closing here. All options are exposed as cli parameters apart from the three tracked in #497
