### ISSUE TITLE
PR images on master

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#361]
**Describe the bug**
I am running xud-docker master testnet and somehow it looks like it managed to pull the utils container of https://github.com/ExchangeUnion/xud-docker/pull/343

throwing 
```
Warning: Using deprecated field "external". Please use "mode" instead.
Warning: Please use field "mode" to specify Infura usage.
```
which also caused another bunch of issues

We have to make sure Travis only pushes to PR branch and only upon merge builds master images. This doesn't seem to be the case right now.

**Comment by reliveyy** [comment]
It's becuase "mode" is already implemented in recent merged PR https://github.com/ExchangeUnion/xud-docker/pull/335. This "mode" PR just updates some config file text.

**Comment by kilrau** [comment]
Ok closing then. But things are not working for me, see other bug issues I opened.
