### ISSUE TITLE
Simplify port exposure in config

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#362]
Off-shoot from https://github.com/ExchangeUnion/xud-docker/issues/282#issuecomment-604241954 :

What we have:

> ```
> [bitcoind]
> #expose-ports = ["8332", "8333", "28332", "28333"]
> [litecoind]
> #expose-ports = ["9332", "9333", "29332:28332", "29333:28333"]
> [geth]
> #expose-ports = ["8545", "30303/udp"]
> [lndbtc]
> #expose-ports = ["9735", "10009", "10010"]
> [lndltc]
> #expose-ports = ["10735", "11009:10009", "11010:10010"]
> [raiden]
> #expose-ports = ["5001"]
> [xud]
> #expose-ports = ["8885", "8886", "8887"]
> ```

What we want:

> ```
> [bitcoind]
> #expose-ports = [8332,8333,28332,28333]
> [litecoind]
> #expose-ports = [9332,9333,29332,29333]
> [geth]
> #expose-ports = [8545,30303]
> [lndbtc]
> #expose-ports = [9735,10009,10010]
> [lndltc]
> #expose-ports = [10735,11009,11010]
> [raiden]
> #expose-ports = [5001]
> [xud]
> #expose-ports = [8885,8886,8887,8080]
> ```

Same for testnet & simnet configs.

**Comment by erkarl** [comment]
Why are we removing the ability to map ports?

**Comment by kilrau** [comment]
We want to do the mapping automatically internally (without the user specifying it in the config)

**Comment by reliveyy** [comment]
<img width="535" alt="Screen Shot 2020-04-04 at 7 28 06 AM" src="https://user-images.githubusercontent.com/4723958/78412464-03b1e580-7646-11ea-8886-120bec483531.png">

**Comment by reliveyy** [comment]
![image](https://user-images.githubusercontent.com/4723958/78412594-79b64c80-7646-11ea-889c-3038e5cf95b4.png)

**Comment by kilrau** [comment]
How did you make this GUI happen? :eyes:
