### ISSUE TITLE
xud ctl global help -> combining all client help outputs

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#369]
EDIT: https://github.com/ExchangeUnion/xud-docker/issues/369#issuecomment-611468621

**Comment by michael1011** [comment]
Slate is rather for API docs. GitBook or Read the Docs would be more appropriate I think

**Comment by kilrau** [comment]
True, point is it should be generated

**Comment by kilrau** [comment]
Or, maybe even better, include xud ctl commands in `help` somehow.
