### ISSUE TITLE
litecoind keeps on exiting after restart

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#37]
Offshoot from https://github.com/ExchangeUnion/xud-docker/issues/38 and reason why `xud` can't connect to litecoind after restart of container/machine:

* `rm -rf ~/.xud-docker/testnet/data/litecoind` - resync - all is good
* but once litecoind was stopped or the machine rebooted, litecoind container keeps on exititing because it can't read some block data
* it looks like docker stop doesn't manage to gracefully shutdown litecoind

**Comment by reliveyy** [comment]
https://bitcoin.stackexchange.com/questions/8787/failed-to-read-block
https://github.com/bitcoin/bitcoin/issues/8081

The solution I can find is using command line option `-reindex`. But with this option litecoind will re-sync from the beginning. I don't think it's a good solution for the user.
And I also notice that bitcoind doesn't have this broken data crashing problem.

**Comment by kilrau** [comment]
I'd like to test something:
1. delete `/data/litcoind`, sync testnet from scratch, bash into litecoind container and shut down gracefully via rpc. Then down container.
2. `docker-compose up -d litecoind`. See if it works.

**Comment by kilrau** [comment]
Adding a fresh litecoind log here soon (resyncing).

**Comment by kilrau** [comment]
In some tests we verified that litecoind's graceful shutdown is triggered on `docker stop litecoind` but looks like it doesn't finish all it has to do before docker kills. Trying `stop_grace_period: 1m`.

**Comment by kilrau** [comment]
Problem: host reboot or `docker stop litecoind` does not care about the docker-compose yml file. 

Patching the entry script should be the way to go:
https://medium.com/@manish_demblani/docker-container-uncaught-kill-signal-d5ed22698293

Let's do it for *all* containers to be on the safe side.

**Comment by kilrau** [comment]
Tested:
### t0 litecoind syncing
`ltc	Syncing 0.83% (8347/1003999)`
### t1 `docker stop`
```
> docker stop 3d68ba19d202
3d68ba19d202
```
### t2 log shows complete shutdown
```
litecoind_1  | Stopping PID 6
litecoind_1  | 2019-06-19T09:53:07Z tor: Thread interrupt
litecoind_1  | 2019-06-19T09:53:07Z Shutdown: In progress...
litecoind_1  | 2019-06-19T09:53:07Z torcontrol thread exit
litecoind_1  | 2019-06-19T09:53:07Z addcon thread exit
litecoind_1  | 2019-06-19T09:53:07Z opencon thread exit
litecoind_1  | 2019-06-19T09:53:07Z net thread exit
litecoind_1  | 2019-06-19T09:53:07Z msghand thread exit
litecoind_1  | 2019-06-19T09:53:07Z scheduler thread interrupt
litecoind_1  | 2019-06-19T09:53:07Z Dumped mempool: 3e-06s to copy, 0.003441s to dump
litecoind_1  | 2019-06-19T09:53:15Z Shutdown: done
````
### t3 `docker-compose up -d litecoind`
Syncing continues without issues (`ltc	Syncing 1.45% (16220/1113654)`)
### t4 YAY
