### ISSUE TITLE
Install docker with convenience script 

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#377]
After the prerequisite check of the os name and whether or not docker is already installed, include and execute the docker convenience script. It will reduce the setup time considerably vis a vis manual downloading. 
```
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh
```

**Comment by kilrau** [comment]
https://get.docker.com/

**Comment by kilrau** [comment]
The https://get.docker.com/ script has the same problem, that it doesn't recognize newer ubuntu versions (like 19.10 or 20.04) yet:
```
# Executing docker install script, commit: 442e66405c304fa92af8aadaa1d9b31bf4b0ad94
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
[sudo] password for kilrau: 
+ sudo -E sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'
+ sudo -E sh -c 'curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null'
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list'
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
E: The repository 'https://download.docker.com/linux/ubuntu focal Release' does not have a Release file.
```
Maybe we can maintain a fork fixing that up.

**Comment by kilrau** [comment]
Moved this down a bit, waiting for ubuntu 20.04 stable to be released and after successfully testing the install script on 18.04 and 20.04 we can start using this script and recommend these two ubuntu versions in the docs. We should also test this on debian and macOS.

**Comment by kilrau** [comment]
ubuntu 20.04 and other new distro releases keep docker fairly up-to-date in their packet managers, lowering prio
