### ISSUE TITLE
[Overview] xud not connected to lnds, raiden

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#38]
Status Overview:
* litecoind keeps exiting because of corrupt blockchain data (https://github.com/ExchangeUnion/xud-docker/issues/37) 
* lndltc keeps crashing and being restarted if litecoind container is down (https://github.com/ExchangeUnion/xud-docker/issues/43)
* Raiden still has the issue of geth not catching up with the ropsten testnet (https://github.com/ExchangeUnion/xud-docker/issues/44)

**Comment by kilrau** [comment]
```
> lndbtc-lncli getinfo
{
	"version": "0.6.1-beta commit=v0.6.1-beta-rc2",
	"identity_pubkey": "03aa43ec9de129585386f6b06bb2a0843647a8d7db352c58ed0ad5de7d208761d4",
	"alias": "lndbtc",
	"num_pending_channels": 0,
	"num_active_channels": 0,
	"num_inactive_channels": 0,
	"num_peers": 0,
	"block_height": 1543044,
	"block_hash": "0000000000000394838161178e48c9d87c46fe80ce76e803b9de817a59b29ca0",
	"best_header_timestamp": 1560424111,
	"synced_to_chain": true,
	"testnet": true,
	"chains": [
		{
			"chain": "bitcoin",
			"network": "testnet"
		}
	],
	"uris": null

```

but still


```
xud_1        | 13/06/2019 11:15:54.744 [RAIDEN] error: Error: connect ECONNREFUSED 172.22.0.4:5001
xud_1        |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
xud_1        | 13/06/2019 11:15:54.744 [RAIDEN] error: could not verify connection to raiden at raiden:5001, retrying in 5000 ms
xud_1        | 13/06/2019 11:15:54.745 [LND] info: LndClient status: Disconnected
xud_1        | 13/06/2019 11:15:54.745 [LND] error: could not verify connection to lnd at lndbtc:10009, error: {"code":12,"metadata":{"_internal_repr":{}},"details":"unknown service lnrpc.Lightning"},
xud_1        |           retrying in 5000 ms
xud_1        | 13/06/2019 11:15:54.745 [LND] info: LndClient status: Disconnected
xud_1        | 13/06/2019 11:15:54.745 [LND] error: could not verify connection to lnd at lndltc:10009, error: {"code":12,"metadata":{"_internal_repr":{}},"details":"unknown service lnrpc.Lightning"},
xud_1        |           retrying in 5000 ms
```

**Comment by kilrau** [comment]
As just discussed on the call:
P0: figure out why the grpc connection to the lnd's is not working
P1: figure out why raiden seems not to be listening on 5001

**Comment by reliveyy** [comment]
I find the lnd not available problem. It's because the macaroon is not available somehow. So this is the reason I always see "Cannot read property 'blockheight' of undefined" like  https://github.com/ExchangeUnion/xud/issues/1011

**Comment by kilrau** [comment]
macaroons get created automatically on default by lnd. Please double check you didn't switch `no-macaroons=true` in `lnd.conf`

**Comment by kilrau** [comment]
Update on what's happening: setting up ssh & ssh port forwarding between `xud` and `lndbtc` to simulate `lndbtc` running locally in the `xud` container. Like this we can narrow down the problem.

E.g. the generated macaroons are only good for local access

**Comment by kilrau** [comment]
TBD: how to move automatically generated macaroon file from the lnd container into the xud container

**Comment by kilrau** [comment]
update: lnd's working now by setting host in `xud.conf` to
```
[lnd.BTC]
disable = false
host = "lndbtc"
```
and
```
[lnd.LTC]
disable = false
host = "lndltc"
```

Raiden still has the issue of geth not catching up with the ropsten testnet:
`raiden_1     | Waiting for the ethereum node to synchronize.`

https://github.com/ethereum/go-ethereum/issues/14338
https://github.com/ethereum/go-ethereum/issues/16147
https://stackoverflow.com/questions/50858538/why-is-my-ethereum-block-number-0-in-geth-even-though-the-sync-is-nearly-comple

**Comment by kilrau** [comment]
closed by https://github.com/ExchangeUnion/xud-docker/commit/e2520dc91eabd439201abd1b8b9cec676b76dbd4
