### ISSUE TITLE
LND-Neutrino: admin macaroon not created after create, xud lnd status stuck

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#382]
Two issues:
- [ ] In neutrino mode (only neutrino, with full-nodes there is no problem), lnd doen't unlock automatically on first start of environment (after `create`) because the admin macaroon doesn't seem to exist yet:
```
testnet > lndbtc-lncli getinfo
[lncli] unable to read macaroon path (check the network setting!): open /root/.lnd/data/chain/bitcoin/testnet/admin.macaroon: no such file or directory
testnet > lndltc-lncli getinfo
[lncli] unable to read macaroon path (check the network setting!): open /root/.lnd/data/chain/litecoin/testnet/admin.macaroon: no such file or directory
```
status in xud: `lnd-xTC is WaitingUnlock`.

Restarting lnd's solves the admin macaroon issue and lnd's get unlocked successfully

**Comment by kilrau** [comment]
Updates? @sangaman

**Comment by kilrau** [comment]
If the final verdict is that we don't know why lnd is behaving this way, could you work with @reliveyy on how to reliably detect that lnd's are stuck and trigger  restart? @sangaman

**Comment by kilrau** [comment]
As discussed, we want to start implementing a "restart" module in xud-docker, which watches out for certain events in L1/L2 client logs and restarts containers if certain things happen. Print restarts.

First event:
- watch lndbtc and lndltc logs and restart if `unable to read macaroon path` is found -> restart

Sounds about right? @reliveyy @sangaman

**Comment by reliveyy** [comment]
Sounds good to me. @kilrau

**Comment by sangaman** [comment]
> watch lndbtc and lndltc logs and restart if unable to read macaroon path is found -> restart

Yes this is what I had in mind.

**Comment by kilrau** [comment]
Alright, let's do this. Are you taking this on? @reliveyy

**Comment by reliveyy** [comment]
This "watch out" feature needs a daemon. I prefer to start another container to do this. What do you think about it? @kilrau @sangaman 

```
docker run -v /var/run/docker.sock:/var/run/docker.sock exchangeunion/watchdog --name testnet_watchdog_1
```

In this `watchdog` it could follow other containers log, listen to docker events and take some actions over other containers like start/stop/restart.

**Comment by kilrau** [comment]
Sounds good, let's do it!
