### ISSUE TITLE
Status command should better handle the edge case before xud starts 

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#389]
Before 

`xud is starting... try again in a few seconds`

the `status` command throws 

`│ xud       │ could not connect to xud at localhost:8886, is │`

It could be better handled with hardcoding the xud status to `waiting..` for 4 seconds.

**Comment by kilrau** [comment]
:+1: Let's simply replace `could not connect to xud at localhost:8886, is` and all `Container running` with `Waiting for <name> to come up...`

**Comment by kilrau** [comment]
Interested @hatmer

**Comment by hatmer** [comment]
I wasn't able to reproduce @peartobear's "could not connect to xud" error but I think I fixed it
