### ISSUE TITLE
geth runs with --cache=256 on default

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#400]
I remember we did this to fit geth onto the Pi4 4GB and now that we build off a common config, it uses this value for all architectures. Result: on a powerful machine geth syncs incredibly slow leaving most system resources unused.

Don't ask me why these cache values have little to do with geth's actual RAM consumption, but according to my real-world tests I would roughly define the following cache values as appropriate:
`--cache=256` for 4GB of RAM
`--cache=1024` for 8GB of RAM
`--cache=4096` for 16GB of RAM
`--cache=8192` for 32GB of RAM

Options:
- I'd prefer to get the available RAM from docker somehow, but couldn't really find if/how that's possible
- use something like `free -m` to detect available RAM and set geth cache accordingly. Problem: error prone because systems are different (e.g. doesn't exist on macos)

**Comment by michael1011** [comment]
Sounds really error prone. Maybe make the `cache` argument of GETH configurable in the config?

**Comment by reliveyy** [comment]
I think we can detect memory capacity inside the container and make `--cache` option adaptive. I know containers' memory capacity are the same as docker machine's if you do not specify some memory opitons when you creating the container.

**Comment by michael1011** [comment]
An option. But I would not just assume that all the free memory of the machine is free real estate for the GETH cache

**Comment by reliveyy** [comment]
> An option. But I would not just assume that all the free memory of the machine is free real estate for the GETH cache

Yes. Since the --cache is a fixed value but the real memory usage changes all the time. So it's better leave this option to the end user and we do apply geth default cache size.

**Comment by reliveyy** [comment]
And if the available memory is smaller than default geth cache size. We shrink the cache size to fit the end user's memory, otherwise the environment may not be able to launch successfully. And this resource adaptive behaviour should be applied to all nodes for memory and disk size.

**Comment by kilrau** [comment]
Alright, closing. I did bump up https://github.com/ExchangeUnion/xud-docker/issues/258 - it should be fairly easy @reliveyy
