### ISSUE TITLE
List of Installation troubles

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#407]
**Introduction**

Just trying install xud-docker for each type of network:
1. _Simnet_ - only lnd-btc starts correctly;
2. _Testnet_ using own nodes (nodes from exchange union docker images)_ - only lnd-btc starts correctly after several restarts of docker containers 
3. _Mainnet using Neutrino and Infra nodes_ - finally, I got all worked nodes, but containers has been restarted too.

I don't create separate issue for each problem that I met during installation attempts because some of them can be 'works as designed' features and its just my misunderstanding of some concepts. It can be done after discussion.

**Configuration**
 - Ubuntu 18.04.3 LTS, 250 SSD, 16 GB RAM
 - Docker 18.09.9

**Simnet**

*Versions of containers*

exchangeunion/xud:1.0.0-beta.2-simnet                 
exchangeunion/raiden:0.100.5a1.dev162-2217bcb-simnet   
exchangeunion/lnd:0.8.2-beta-simnet 
exchangeunion/lnd:0.8.2-beta-simnet             
exchangeunion/utils:latest

*List of problems*

- ~~Lnd-ltc node cant start correctly because of "Unable to create chain control: open /root/.ltcd/rpc.cert: no such file or directory" error.~~(will be fixed by #385 ) I checked container, .ltcd folder does not contain rpc.cert file - [simnet_lndltc_node.log](https://github.com/ExchangeUnion/xud-docker/files/4465354/simnet_lndltc_node.log)
- ~~Raiden node cant start because of supervisor trouble.~~(Raiden will be deleted from simnet setup after maintenance) - [simnet_raiden_node.log](https://github.com/ExchangeUnion/xud-docker/files/4465362/simnet_raiden_node.log)
- ~~**No simnet tokens and opened channels after ~30 mins**~~(as described here - docs.exchangeunion.com/start-earning/market-maker-guide). I see ExchangeUnion's peer (listpeers), but balance of btc is 0. I assume that for token getting(channel opening by you) I need all three worked nodes and xud in ready state, but I want to get confirmation of this behavior. [no_tokens_screen.png](https://user-images.githubusercontent.com/29906866/79054578-d4573600-7c4e-11ea-94cf-5eb4a94a5c21.png)

*Notes*

- ~~**cli does not ask me for password and seed phrase**~~ - its a little bit destructive for UX. I was really confused because I did not understand how the nodes work without a password and seed phrases (I assumed that you create wallets without user actions). Also, I found nothing about this feature (no password asking when use simnet). Maybe, information about that should be added to docs.exchangeunion.com as a note OR just add password asking in simnet flow.

*Steps to Reproduce*

0. delete all docker images and containers
1. curl https://raw.githubusercontent.com/ExchangeUnion/xud-docker/master/xud.sh -o ~/xud.sh
2. bash ~/xud.sh
3. choose Simnet
4. wait for xucli

**Testnet**

*Versions of containers*

exchangeunion/xud:1.0.0-beta.2
exchangeunion/raiden:0.100.5a1.dev162-2217bcb
exchangeunion/lnd:0.9.0-beta-ltc
exchangeunion/lnd:0.9.2-beta
exchangeunion/geth:1.9.12
exchangeunion/litecoind:0.17.1
exchangeunion/bitcoind:0.19.1
exchangeunion/utils:latest

Created by bash xud.sh and choosing Testnet in Menu.

*List of problems*

- ~~99,9% trouble of geth synchronization~~ (Hint will be added)  - cant synchronize geth testnet for a night. I undestand that its not XUD problem but its really headache. It may be worth adding a note about this and solutions to the Tips 'n Tricks section (https://docs.exchangeunion.com/start-earning/market-maker-guide).
- **No Waiting For Sync status for lnd and riden nodes after installation** (when ltc, btc, geth nodes in sync state) 
- ~~Nodes stuck in Container running state after sync finishing~~ (found a duplicate - https://github.com/ExchangeUnion/xud/issues/1457) 
[screen_1](https://user-images.githubusercontent.com/29906866/79055905-69f7c300-7c59-11ea-971d-27e9f52392c4.png), [screen_2](https://user-images.githubusercontent.com/29906866/79055915-7f6ced00-7c59-11ea-9cae-8043c1a6262b.png). To get Actual status restart of container requiried.
- ~~lndbtc in Ready state when bitcoind in Sync State (Expected state for lndbtc is Waiting for sync) / hard to reproduce.~~ (Found a duplicate https://github.com/ExchangeUnion/xud/issues/1419) Bitcoind was in Ready state and after some time status was changed to Sync, but status of lndbtc was not changed [screen_3](https://user-images.githubusercontent.com/29906866/79056039-f0f96b00-7c5a-11ea-84c1-2f043757a299.png), [screen_4](https://user-images.githubusercontent.com/29906866/79056041-f5be1f00-7c5a-11ea-81ab-7c2d21d36ecb.png). 
- ~~**Cant get Ready status for lndltc node after litecoind sync because of connection refused error.**~~ (Install -> wait litecoind sync -> restart lndltc node (Because of previous problem; to get correct status)  -> Node stuck in Wallet locked node / hard to reproduce). When I tried unlock node using xuc-cli or lndltc-cli I got connection refused error - [screen_5](https://user-images.githubusercontent.com/29906866/79055504-51d27480-7c56-11ea-8efd-a54d80928125.png), [screen_6](https://user-images.githubusercontent.com/29906866/79055520-6dd61600-7c56-11ea-8152-797ce6d67fce.png). After several restarts of lndltc and xud_node I restarted litecoind and got FATAL Error like 'cant read blocks from the disk' and litecoind starts synchronization from beginning. And after that I gave up.

*Steps to Reproduce*

0. delete all docker images and containers
1. curl https://raw.githubusercontent.com/ExchangeUnion/xud-docker/master/xud.sh -o ~/xud.sh
2. bash ~/xud.sh
3. choose Testnet
4. wait for xucli

**Mainnet with Neutrino/Infra**

**There were no unique problems**, just containers that were stuck in Container running state and admin.macroon issue #382 ([screen_7](https://user-images.githubusercontent.com/29906866/79073323-9578bd00-7cee-11ea-875a-50930b74e000.png)), but after some restarts I finally got 4 Ready states.

**Comment by kilrau** [comment]
Thank you so much for testing all this - good and bad news at the same time: we are aware of *most* of the issues :/ 

Since we would like to work closer with you to confirm our solutions for each, consider joining our developer chat at https://discordapp.com/invite/YgDhMSn

**Comment by raladev** [comment]
Issue for geth hint was added and also I found other issues that looks like my problems;
Therefore, I edit first post to actualise it.

**Comment by kilrau** [comment]
> Simnet

Simnet is currently undergoing a revamp, please refrain from using it until this is complete (also the reason why we marked it as "under maintenance" [here](https://docs.exchangeunion.com/start-earning/market-maker-guide#three-networks). Raiden will not be part of the simnet anymore in future, but connext instead and channel opening bot is currently being fixed. We are fixing this as a priority, will go through the issue you encountered before we go live again.

> Testnet
> 99,9% trouble of geth synchronization 

Agree, opened this PR: https://github.com/ExchangeUnion/docs/pull/94 

> No Waiting For Sync status for lnd and riden nodes
Was this with the full setup (bitcoind/litecoind/geth)? Issues we are aware: all things container status stuck with the **light setup**: https://github.com/ExchangeUnion/xud-docker/issues/382 & https://github.com/ExchangeUnion/xud/issues/1457

> Cant get Ready status for lndltc node after litecoind sync because of connection refused error.

Do you happen to still have logs? Litecoin rewinding blocks (looks like syncing again from scratch but actually doesn't download anything and hence should me much faster) is an issue we encounter since early on and we gave up trying to fix it after @reliveyy spent about a month trying to get litecoind not to corrupt it's own data. We can give it another shot though.

**Comment by raladev** [comment]
> Raiden will not be part of the simnet anymore in future, but connext instead and channel opening bot is currently being fixed. 
Ok, I crossed out Raiden problem because of the deletion.

> **No Waiting For Sync status for lnd and riden nodes**
That was with the full setup (Testnet) and with the light setup (Mainnet).

> **Nodes stuck in Container running state after sync finishing**
> > Was this with the full setup (bitcoind/litecoind/geth)? Issues we are aware: all things container status stuck with the **light setup**: #382 & [ExchangeUnion/xud#1457](https://github.com/ExchangeUnion/xud/issues/1457)
That too was with the full setup (Testnet) and with the light setup (Mainnet).

If you need full logs of all nodes for both cases above, I can reproduce them again, they are easily reproducible.

> > Cant get Ready status for lndltc node after litecoind sync because of connection refused error.
> Do you happen to still have logs? Litecoin rewinding blocks (looks like syncing again from scratch but actually doesn't download anything and hence should me much faster) is an issue we encounter since early on and we gave up trying to fix it after @reliveyy spent about a month trying to get litecoind not to corrupt it's own data. We can give it another shot though.

I have only sixth screen(screen_6) with logs of xud where I tried to unlock the node and got Could not verify connection error.

Regarding litecoind re-sync problem, I have no logs and screens, but I can try to reproduce it again if this works out. Litecoin testnet sync does not take much time.

**Comment by kilrau** [comment]
Let's see this as the ultimate test for beta.4.

**Comment by raladev** [comment]
only this one still exists - No Waiting For Sync status for lnd and riden nodes after installation (when ltc, btc, geth nodes in sync state)

I closed this issue and will open another one to determine correct statuses for each stage.
