### ISSUE TITLE
Issues on macOS

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#411]
This issue collects xud-docker macOS related issues.

**Comment by kilrau** [comment]
Create prompt loop on macOS:
![image](https://user-images.githubusercontent.com/19181985/79242252-5c6a5500-7e74-11ea-9847-eae1bfec780a.png)

https://paste.ubuntu.com/p/DvW5MWfmnK/

**Comment by kilrau** [comment]
Could you both please run https://github.com/ExchangeUnion/xud-docker/pull/429 on your mac to see if there are any issues left? @peartobear @reliveyy 

If not, we can close here.

**Comment by peartobear** [comment]
This problem is resolved in `connext-yy` branch. This issue can now be closed.
