### ISSUE TITLE
bitcoind/litecoind/geth images pulled when its not necessary

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#414]
**Describe the bug**
    When use neutrino/infra for lightweight setup, launcher pulls bitcoind/litecoind/geth images and does not use them.

**To Reproduce**
1. Perform lightweight setup
2. See console and docker images

**Expected behavior**
1. No console messages about missing unnecessary nodes
2. No unnecessary images pulling

**Comment by kilrau** [comment]
Nice catch!
