### ISSUE TITLE
"Couldn't find docker" error message

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#426]
![image](https://user-images.githubusercontent.com/19181985/79961421-fccd0480-8486-11ea-88a2-dbd238479c96.png) by @hatmer 

Our script should say `Couldn't find docker running, is it installed? If not, follow the install instructions: https://docs.docker.com/engine/install/`

**Comment by hatmer** [comment]
Also the script should ask if `./xud.sh` was run as sudo, since without sudo the same problem occurs silently. In fact this may be the real reason for this problem, I am verifying now.

**Comment by kilrau** [comment]
Doesn't have to be run with sudo if you user is in the docker group, see https://docs.docker.com/engine/install/linux-postinstall/. We should add that hint somehow too.

**Comment by hatmer** [comment]
I verified that it was a sudo issue only. I had installed docker using snap so I couldn't easily start/stop the daemon, but the reason `docker pull` failed was a permissions problem. PR is up.

**Comment by hatmer** [comment]
I think unfamiliarity with Docker may be a common problem amongst traders so this is probably a good thing to have a hint for
