### ISSUE TITLE
Auto-build xud:latest when xud master changes

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#438]
Currently the detection only shows image modified in the project's git history. But since we introduced **lastest** tag recently it needs some inhancements to let tools scripts know that **latest** tag is changed not only because of the Dockerfile is changed but also the upstream branch has new commits.

**Comment by kilrau** [comment]
Make special case for `latest` to check:
- check dockerhub xud image `commit hash`
- check xud GitHub repository `commit hash`
- determine if needs to be rebuild or not

**Comment by reliveyy** [comment]
The best timing to build a new xud image is when new commits appended to monitored xud branches like master.

**Comment by kilrau** [comment]
Is it possible to have some hook that triggers a travis build for `xud:latest` as soon as something was merged into `xud` master = latest commit hash changed? @reliveyy

**Comment by reliveyy** [comment]
We could inspect `lib/Version.ts` or `.git` to get current xud revision. But this needs to download at least one layer of the xud image. And I don't think it is lightweight enough to get such metadata of xud image. I think a better approach is put **application** revision and branch information into image labels. That means the old images on the dockerhub registry won't have these information.

**Comment by reliveyy** [comment]
I'd like to introduce two new labels:

* com.exchangeunion.application.revision
* com.exchangeunion.application.branch (tag sometimes. E.g. master, 1.0.0-beta.2)

We will add these to new images and try to add make up for old images.

**Comment by kilrau** [comment]
Current issues:
- `xud-docker-bot` reports `ExchangeUnion/xud branch master was pushed (Merge pull request #1564 from ExchangeUnion/chore/update-seeds` but actually image are not there
- `xud-docker-bot` has a local copy of the `xud-docker` repo and currently doesn't run `git remote prune origin`. So it tries pushing to delted branches.

**Comment by kilrau** [comment]
Should happen:
- new commit/merge in xud master sends latest commit hash to xud-docker-bot
- xud-docker-bot compares this commit hash with xud:latest image on dockerhub
- if different, it triggers a new build using xud master with this commit hash
- it checks that build was successful. If it was not successful, it restarts 3x
- all have messages in the xud-docker-bot, especially failed builds should be clearly marked :rotating_light:

**Comment by raladev** [comment]
Current status:
- [ ] It does not work fully if i understand correctly, i dont see any builds in travis because of yesturday's merges (4 PRs) for docker master branch or for branches that use xud master image
- [ ] Also after xud commit to branch that connected with branch in xud-docker repo build was not triggered too. (If i remember correctly, it is part of this issue too).

**Comment by kilrau** [comment]
The last merged PR triggered a build: https://travis-ci.org/github/ExchangeUnion/xud-docker/builds

Once @reliveyy pushed his xud-dockerb-bot discord `buildxudlatest` command, I think we can close this @raladev

**Comment by kilrau** [comment]
All done here, we will open new issues for issues that come up.Good stuff @reliveyy :+1:
