### ISSUE TITLE
Geth can't catch up with ropsten

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#44]
* Raiden still has the issue of geth not catching up with the ropsten testnet:
`raiden_1     | Waiting for the ethereum node to synchronize.`

https://github.com/ethereum/go-ethereum/issues/14338
https://github.com/ethereum/go-ethereum/issues/16147
https://stackoverflow.com/questions/50858538/why-is-my-ethereum-block-number-0-in-geth-even-though-the-sync-is-nearly-comple

**Comment by kilrau** [comment]
Strong consideration: change to parity

**Comment by michael1011** [comment]
@kilrau @reliveyy especially because the fast sync of Parity works perfectly fine and we do need that for mainnet since syncing Geth onk mainnet normally will take forever.

**Comment by kilrau** [comment]
closed by https://github.com/ExchangeUnion/xud-docker/commit/e2520dc91eabd439201abd1b8b9cec676b76dbd4
