### ISSUE TITLE
"Restarted lnd should be locked" error during restart phase

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#461]
**Describe the bug**
Sometimes I started to get following errors for all new clear simnet installations on restart phase:

![Screenshot from 2020-05-18 14-57-27](https://user-images.githubusercontent.com/29906866/82210707-3bd06780-9918-11ea-9632-9bda55aa680d.png)

Can be fixed only by host machine restart.

**Logs of 3 nodes for 2 cases**
[xud_python.log](https://github.com/ExchangeUnion/xud-docker/files/4643955/xud_python1.log)
[xud_python.log](https://github.com/ExchangeUnion/xud-docker/files/4643956/xud_python.log)
[lndltc_python.log](https://github.com/ExchangeUnion/xud-docker/files/4643957/lndltc_python.log)

Errors appeared ~ in 12:07 for the second case:

[xud_15_07_python.log](https://github.com/ExchangeUnion/xud-docker/files/4643987/xud_15_07_python.log)
[lndltc_15_07_python.log](https://github.com/ExchangeUnion/xud-docker/files/4643988/lndltc_15_07_python.log)
[lndbtc_15_07_python.log](https://github.com/ExchangeUnion/xud-docker/files/4643989/lndbtc_15_07_python.log)

**Comment by kilrau** [comment]
As far as I understand lnd's were stuck in this `Waiting for ...` and never came up, right? Happened more than once?

**Comment by raladev** [comment]
> As far as I understand lnd's were stuck in this `Waiting for ...` and never came up, right? Happened more than once?

Depends on lnd logs I can say only that lnd just dont restarted and yes, it stucked in `Waiting for ...` status and after 100 sec I got exception.

Got it twice on previous week and once today.

`            # [lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.
            for i in range(10):
                exit_code, output = c.exec_run(f"lncli -n simnet -c {chain} getinfo")
                result = output.decode()
                if exit_code == 0:
                    return
                time.sleep(10)

            raise RuntimeError("Restarted lnd should be locked")
`
