### ISSUE TITLE
'lnd-LTC: 14 UNAVAILABLE' error appears sometimes during creation phase

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#471]
**Describe the bug**
'lnd-LTC: 14 UNAVAILABLE' error appears sometimes during creation phase. It defiantly connected with tor connection and bootstraping phase.

**To Reproduce**
1. Perform testnet(neutrino mode)/simnet installation 
2. Create new xud env

**Actual result**
[Screenshot from 2020-05-21 14-30-00](https://user-images.githubusercontent.com/29906866/82554990-99122600-9b6f-11ea-81e2-f9683d29bc78.png)

**Logs for testnet(neutrino) case**

[ltc_lndbtc.log](https://github.com/ExchangeUnion/xud-docker/files/4662217/ltc_btc.log)
[ltc_lndltc.log](https://github.com/ExchangeUnion/xud-docker/files/4662218/ltc_ltc.log)
[ltc_xud.log](https://github.com/ExchangeUnion/xud-docker/files/4662219/ltc_xud.log)

**Note**
- In the logs above my lndltc node died fully, but for attempt before that it just stuck in Bootstrapping 57% phase for ~5 mins and continues work correctly after that.
- With vpn to Frankfurt I got successful installation.

**Comment by reliveyy** [comment]
My failure test logs:
[lndbtc.log](https://github.com/ExchangeUnion/xud-docker/files/4662209/lndbtc.log)
[lndltc.log](https://github.com/ExchangeUnion/xud-docker/files/4662210/lndltc.log)
[xud.log](https://github.com/ExchangeUnion/xud-docker/files/4662211/xud.log)

**Comment by reliveyy** [comment]
The error should be related to xud `[xud-backup] Waiting for backup_dir value`

**Comment by raladev** [comment]
> The error should be related to xud `[xud-backup] Waiting for backup_dir value`

I dont think so, Xud env was created successfully and next step for it is find backup dir, but u cant define it as a user because u stuck on creation phase for lndltc. Therefore u got Waiting spam in xud logs but it my opinion it does not connected with lndltc behaivour.

**Comment by reliveyy** [comment]
> > The error should be related to xud `[xud-backup] Waiting for backup_dir value`
> 
> I dont think so, Xud env was created successfully and next step for it is find backup dir, but u cant define it as a user because u stuck on creation phase for lndltc. Therefore u got Waiting spam in xud logs but it my opinion it does not connected with lndltc behaivour.

Yes. You are right. It's a false alarm.

**Comment by raladev** [comment]
Closed, solved by https://github.com/ExchangeUnion/xud-docker/issues/472.
