### ISSUE TITLE
Cant enter to existing environment after utils container closing

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#486]
**To Reproduce**
1. bash xud.sh -> testnet -> walk through installation procces
2. unlock xud node
3. print exit
4. bash xud.sh -> testnet -> wait

**Actual result**
Stuck on Warming Up state, launcher checks lnd status in infinite loop.
[Screen](https://user-images.githubusercontent.com/29906866/83278009-92248c80-a1db-11ea-82e7-e1cb42636149.png)
[testnet.log](https://github.com/ExchangeUnion/xud-docker/files/4702772/testnet.log)

**Comment by kilrau** [comment]
Just reproduced this with an existing simnet environment. Looks like the conditions for the `🏃 Warming up...` lnd check to determine them as healthy is wrong @reliveyy . If you are not sure which one to use, let's discuss it here.
