### ISSUE TITLE
Improve help UX

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#492]
**Is your feature request related to a problem? Please describe.**
Based on https://github.com/ExchangeUnion/xud-docker/pull/366#issuecomment-636771599
1. Help is printed after network choosing that leads to misunderstanding because user thinks that there is no help and it is just a installation flow
2. Help is not user friendly

**Solutions for first**
1. If --help option is used then print message "Help option is used, help will be printed after network choosing"
2. Integrate help message into xud.sh script (only help message) and print it before network choosing
3. Move network choosing into utils - https://github.com/ExchangeUnion/xud-docker/pull/366#issuecomment-636868594

**Solution for second**
1. Add options that can be used and examples instead of 'GETH.MODE'.

**Comment by reliveyy** [comment]
From https://github.com/ExchangeUnion/xud-docker/pull/366#issuecomment-637565064

Make sure the syntax of `--node.expose-ports` is included in the `--help` output.

```
--node.expose-ports "8080,8081:8082"
```

**Comment by kilrau** [comment]
Addition from https://github.com/ExchangeUnion/xud-docker/issues/541#issuecomment-645317610:
> I would suggest overriding the `help` command with a list of all executables and their purposes

**Comment by kilrau** [comment]
I think we are good with the help UX as of now.
