### ISSUE TITLE
[simnet] upgrade to new xud and lnd

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#5]

**Comment by reliveyy** [comment]
* xud 1.0.0-prealpha.4
* lnd 0.6.1-beta-rc2

**Comment by kilrau** [comment]
Ehm it should be

xud 1.0.0-prealpha.11 (master)
lnd 0.6.1-beta (release)

**Comment by kilrau** [comment]
Please close when updated @reliveyy
