### ISSUE TITLE
docker auto-build for external daemons

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#534]
- [x] new commit in [arby(master)](https://github.com/ExchangeUnion/market-maker-tools/commits/master) -> `arby:latest`
- [x] new commit in [boltzd(master)](https://github.com/BoltzExchange/boltz-lnd/commits/master) -> `boltzd:latest`

**Comment by reliveyy** [comment]
@kilrau And what about connext:latest?

**Comment by kilrau** [comment]
We will do that one manually since server and client version have to be in sync and there are breaking changes in sight.

**Comment by reliveyy** [comment]
Closed by #544 and #549.
