### ISSUE TITLE
[Boltz integration] Sanity checks for invoice payability before `createswap` 

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#540]
Sanity check to see if the invoice is payable before throwing `no route` error during `createswap` and `createreverseswap`

**Comment by kilrau** [comment]
Looking at this again, I understand and agree that this is needed but I am not sure I understand why this should be done by xud-docker and not by boltzd directly. If you agree, consider moving this to your repos at boltz.
