### ISSUE TITLE
Non heirarchal help is confusing 

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#541]
The help menu inside docker container looses context of `lndbtc-lncli` and `lndltc-lnci` which severely handicaps the user

**Comment by michael1011** [comment]
I would suggest overriding the `help` command with a list of all executables and their purposes
@kilrau

**Comment by kilrau** [comment]
Yeah why not!

**Comment by kilrau** [comment]
Included in https://github.com/ExchangeUnion/xud-docker/issues/492. Closing here.
