### ISSUE TITLE
`bash xud.sh --dev` flag -> use local images if available

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#561]
**Is your feature request related to a problem? Please describe.**
Our change to comparing hashes only to check for updates creates an issue for developers where it always pulls images from the cloud instead of using the local one because the image hashes differ. The developer has to push images, let travis build and then let xud-docker pull in order to test changes. That takes much more time than building locally. 

**Describe the solution you'd like**
xud-docker to accept a `--dev` flag that simply uses the newest local image (if there is one) for a specific docker image tag. If there is no local image -> pull from cloud/regular behavior.

**Describe alternatives you've considered**
Fixing up our timestamp comparison (detecting if cloud is newer or local), but this proved to be difficult to get right so we got rid of it.

**Comment by reliveyy** [comment]
FYI, this `--dev` option already existed but it has some differences with this issue description. It is just specifed to use local **utils** only. While this issue is more about letting `--dev` as swich which implies auto-applying local built images.

**Comment by kilrau** [comment]
We now have  `--dev` and `--use-local-images` which, in combination, achieve this.
