### ISSUE TITLE
Perform data migration before upgrade, downgrade or branch switching

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#66]

**Comment by kilrau** [comment]
Is that still needed? @reliveyy

**Comment by reliveyy** [comment]
I think it's still needed. Ideally every container takes care of it's own data and migrate data by themselves, report errors when migration failed. Xud-docker has its own data (the user's configuration) and should be resposible for such data migration. And it also need to collect all migration errors and show it to the user.
