### ISSUE TITLE
add standalone xud deployment documentation

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#662]
From discord feedback:
> Thanks for reply guys! Will appreciate "dockerless" deployment guide, because my cheap crappy VPS don't support docker haha). The same about docker-compose setup. Your setup worked perfectly in my personal case, but big enterprises are not so flexible and always have their own strong opinions about how things should be deployed. For example if I propose XUD for company where I'm working, I have to write docker-compose files by hand, give them to devops which will provide secret environment variables in our environment etc. Docker-compose is common thing today, it's very nice to have actual examples of compose files.

**Comment by kilrau** [comment]
I seperated the "dockerless"/native installation guide into https://github.com/ExchangeUnion/docs/issues/107.

This here remains about docker-compose compatibility. Checking in here, would it be much work to make things docker-compose compatible? @reliveyy If not, we should get this done and provide a `sample-docker-compose.yml`
