### ISSUE TITLE
Small `status` fixes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#663]
- [ ] `status` shows `Can't connect to Connext node` for several seconds while the connext client is loading:

```
testnet > logs connext
2020-08-12 17:12:44,368 INFO Set uid to user 0 succeeded
2020-08-12 17:12:44,379 INFO supervisord started with pid 1
2020-08-12 17:12:45,383 INFO spawned: 'connext' with pid 7

> @connext/rest-api@7.2.0 start /app
> npm run build && npm run prod


> @connext/rest-api@7.2.0 build /app
> npm run clean:build && npm run compile

2020-08-12 17:12:47,065 INFO success: connext entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

> @connext/rest-api@7.2.0 clean:build /app
> rm -rf ./build


> @connext/rest-api@7.2.0 compile /app
> tsc -p tsconfig.json


> @connext/rest-api@7.2.0 prod /app
> node ./build/src
```
and only switches to `Ready` once connext successfully initialized. This is bad UX, since it indicates something is wrong.

It should print the usual `Waiting for connext to come up...` message in that stage.

- [ ] xud status should be `Ready` as soon minimum one swap client has a channel. At the moment it shows `Waiting for channels` unless **all** clients have channels.

**Comment by reliveyy** [comment]
I've seen this status too.

**Comment by rsercano** [comment]
I can check this unless you want to leave it for first time contributors @kilrau
