### ISSUE TITLE
Persist all connext-store-* folders

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#669]
Due to the changes of connext rest-api-client the connext-store is now namespaced with the public identifier:
```
bash-5.0# pwd
/app
bash-5.0# ls
Dockerfile
LICENSE.md
README.md
build
connext-stderr---supervisor-2_js4f21.log
connext-store
connext-store-indra8izy9k89Q1EFRcHbu4uPFt6P6W5fR2zxf7mWXQYMw5DcYxp92s
```

@reliveyy is it possible to create a wildcard docker volume for persisting folders like `connext-store-indra8izy9k89Q1EFRcHbu4uPFt6P6W5fR2zxf7mWXQYMw5DcYxp92s`?

**Comment by reliveyy** [comment]
I'm afraid not. Could we specify a parent folder of connext-store-*? @erkarl

**Comment by erkarl** [comment]
> I'm afraid not. Could we specify a parent folder of connext-store-*? @erkarl

I was afraid of that. I'll see if changes from rest-api-client side are possible.

**Comment by erkarl** [comment]
Solved by https://github.com/connext/rest-api-client/pull/85
