### ISSUE TITLE
Create fixed-version utils image

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#670]
Currently only master Mainnet has images with fixed version. In other cases it will have **2nd image pulling question** in update checking stage. So a totally fixed-version utils will eliminate the 2nd question.

Related to https://github.com/ExchangeUnion/xud-docker/pull/639

**Comment by kilrau** [comment]
Just for clarification: currently there are 2 update prompts on mainnet if an image, e.g. xud gets bumped from e.g. 1.0.0 to 1.0.1. One for utils update, one for xud update. This issue is about fixing utils to a fixed set of versions which will lead to 1 update prompt only.

**Comment by reliveyy** [comment]
> on mainnet if an image, e.g. xud gets bumped from e.g. 1.0.0 to 1.0.1. One for utils update, one for xud update. This issue is about fixing utils to a fixed set of versions which will lead to 1 update

Yes. If we got one-to-one mapping of utils and other images then we could merge these two questions into one.

**Comment by kilrau** [comment]
We abandoned the launcher approach, so this is not the case anymore. Closing.
