### ISSUE TITLE
Inconsistency between XUD status and synced status printed by getinfo call

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#690]
XUD status shows ready even though the env is out of sync 

![Screenshot 2020-08-26 at 2 39 10 PM](https://user-images.githubusercontent.com/44926540/91284706-e70b7b00-e7a9-11ea-8b40-2b72dca4b026.png)

**Comment by kilrau** [comment]
Thanks for reporting this. But it looks like you are running a very outdated xud-docker version there, this is how it should look like
```
testnet > status
┌───────────┬────────────────────────────────────────────────┐
│ SERVICE   │ STATUS                                         │
├───────────┼────────────────────────────────────────────────┤
│ bitcoind  │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ litecoind │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ geth      │ Ready (light mode)                             │
├───────────┼────────────────────────────────────────────────┤
│ lndbtc    │ Syncing                                        │
├───────────┼────────────────────────────────────────────────┤
│ lndltc    │ Ready                                          │
├───────────┼────────────────────────────────────────────────┤
```

Didn't you get an update prompt?

**Comment by peartobear** [comment]
I did get it but I'm stuck in "Failed to wait for LNDBTC to be ready" so the env is not booting up anymore. It's a bad Tor circuit issue

**Comment by kilrau** [comment]
So it sounds like https://github.com/ExchangeUnion/xud-docker/issues/599 is your actual issue. If so, the only way please try to manually restart lnd via `docker restart` and watch lnd logs if that solves it. We should find an automated way to resolve this tor issue. 

Once you manage to bring up your environment again, I bet above issue is solved through the upgrade. But let's see about that.
