### ISSUE TITLE
The macOS host user's home directory is not accessible in containers

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#717]
After `bash xud.sh` all 3 networks failed to start on macOS with the same error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/__init__.py", line 257, in launch
    config = Config(ConfigLoader())
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/config/config.py", line 25, in __init__
    self.home_dir = self.loader.ensure_home_dir(os.environ["HOST_HOME"])
  File "/usr/local/lib/python3.8/site-packages/launcher-1.0.0-py3.8.egg/launcher/config/loader.py", line 47, in ensure_home_dir
    os.mkdir(hostfs_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hostfs/Users/yy/.xud-docker'
```

![image](https://user-images.githubusercontent.com/4723958/92461091-61e98280-f1fb-11ea-994e-0550307ebc2a.png)

Looks like the way we map `/` to `/mnt/hostfs` doesn't work on macOS anymore

**Comment by kilrau** [comment]
Can you confirm? @peartobear

**Comment by reliveyy** [comment]
> Which macOS version

![image](https://user-images.githubusercontent.com/4723958/92544814-5b055300-f281-11ea-81b2-7f3526e96202.png)

**Comment by kilrau** [comment]
You are using a beta version of docker. Can you please try the latest stable release? @reliveyy 

Other users reported no problems with
- Catalina (10.15.6) and Docker Desktop v2.3.0.4
- Catalina and Docker Desktop v2.2.0.5

**Comment by kilrau** [comment]
Closingin favor of https://github.com/ExchangeUnion/xud-docker/issues/717
