### ISSUE TITLE
After lndltc/lndbtc/connext container restart xud cant connect to them

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#718]
Steps:
1. Start docker env
2. Stop lndltc/lndbtc/connext container
3. Start it again

Actual result:
xud log is full of cert errors.
[Screenshot from 2020-09-09 15-58-23](https://user-images.githubusercontent.com/29906866/92601297-50fd4780-f2b5-11ea-8c13-0ce01c4934d0.png)

Expected result:
connection established sucessfuly

**Comment by kilrau** [comment]
Ehm... this works for me. Just tested on several setups, including mainnet. Could you check again if there was anything special in your environment that could have caused this? @raladev

**Comment by raladev** [comment]
checked again, with new setup all is fine. Closed for now.

**Comment by raladev** [comment]
![Screenshot from 2020-09-17 15-45-48](https://user-images.githubusercontent.com/29906866/93472132-f0958800-f8fc-11ea-856a-766803311fd7.png)
got it again today, will try to reproduce reliably and find the root case.

**Comment by raladev** [comment]
problem maybe connected with snap installation of docker but im not sure.
changing prio to P3.
