### ISSUE TITLE
Make launching containers non-interactive for xud-ui

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#743]
Current state of xud-docker requires user input after starting the script to launch containers.

In order to provide smooth user experience for UI projects we'll need non-interactive mode.

`bash xud.sh --non-interactive --mainnet` should:
1. Start all containers for mainnet
2. Setup temporary backup directory
3. Initialize the wallet with default password `xud-docker` (since we're using aezeed we can change the password later via API call)

**Comment by reliveyy** [comment]
@erkarl I suggest we use command-line options to disable interactive questions.

* `--network simnet` disables interactive networking choosing
* `--wallet-password` disables interactive password setting during wallet creation 
* `--backup-dir` disables interactive backup folder setting and create/restore selection (if no --restore-dir then create) 
* `--restore-dir` disables interactive restore folder setting and create/restore selection (if having --restore-dir then restore)

E.g.

```bash
# Example 1 (create)
bash xud.sh --network testnet --backup-dir ~/.xud-docker/testnet/backup --wallet-password 'secret'

# Example 2 (restore)
bash xud.sh --network mainnet --backup-dir /new/backup/location --wallet-password 'unlock' \
--restore-dir /old/xud-docker/mainnet 

# Example 3 (discard --wallet-password in command-line)
source vault.env # contains XUD_DOCKER_WALLET_PASSWORD='deepsecret'
bash xud.sh --network mainnet --backup-dir ... 
```

P.S. If using non-interactive create then `seed.txt` will be saved under network-dir.

**Comment by reliveyy** [comment]
`--network` is added in https://github.com/ExchangeUnion/xud-docker/pull/750

**Comment by erkarl** [comment]
@reliveyy how would this work for Windows?

Could we provide these options as environment variables?
```
docker run --env ENV_CONFIG="$(cat docker-config.json)" ...
```

**Comment by erkarl** [comment]
> @reliveyy how would this work for Windows?

Making this work on Windows is probably out of context of this issue though.
