### ISSUE TITLE
Make proxy container default / mandatory

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-docker#745]
Reason:
Get reliable status info from one source (proxy api) for xud-ui.

Behavior:
1. proxy container is required container;
2. proxy container has no exposed ports by default; (EDIT: or only exposed to `localhost`, EDIT by @kilrau : TBD!)
3. if some flag is used, then container will expose default port (need to discuss);
4. cli status command should use /api/v1/status results.

**Comment by kilrau** [comment]
A security requirement for this is to limit exposing 8889 and the webserver port to local network (not just bind to 0.0.0.0 and that's it). One idea I have is to use subnetmasks on docker network level.

**Comment by reliveyy** [comment]
> One idea I have is to use subnetmasks on docker network level

FYI, the Docker subnets used in xud-docker are `10.0.1.1/24`, `10.0.2.1/24` and `10.0.3.1/24`. @kilrau
