### ISSUE TITLE
Windows path support

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#757]
It's necessary to run xud script smoothly on Windows. Currently if you type `C:\MyXudBackup` in backup location question it will break the backup functionality.

And addtional fixes are required in setup.sh.

**Comment by kilrau** [comment]
This issue is about making Windows mounting work with `-v /mnt:/mnt/hostfs` to access `C:\` with `/mnt/hostfs/c`.

**Comment by kilrau** [comment]
Without this, `xud-docker` on Windows won't be able to safe state to disk and will sync + create from scratch every time the environment is started.

**Comment by kilrau** [comment]
Closing here in favor of https://github.com/ExchangeUnion/xud-docker/issues/788
