### ISSUE TITLE
Hostfs mouting issue (-v /:/mnt/hostfs)

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker#785]
Known issues when we try to map the whole hostfs into one contianer with `-v /:/mnt/hostfs`

* The macOS FUSE issue (https://github.com/ExchangeUnion/xud-docker/issues/756);
* Link file breaks on Linux (This happens on RaspiBlitz);
```
$ cd /tmp
$ echo 1 > a
$ ln -s $PWD/a b
$ docker run -it --rm --entrypoint cat -v /:/mnt alpine /mnt/tmp/b
cat: can't open '/mnt/tmp/b': Permission denied
```
* Read-write permission too wide for container usage (It's not normal to map "/" into contianers);
* Cannot work on Windows without WSL2 (For more details, see [this SO question](https://stackoverflow.com/questions/64807757/how-to-mount-a-windows-path-volume-inside-a-docker-container));
* Performance issue.

**Comment by reliveyy** [comment]
And I came up with 3 solutions:

1. Use `docker run -it --rm -v /any/path:/mnt:ro alpine` to check any files on host. But it's not perfect becuase it will create an empty folder if it doesn't exist on host. And it cannot handle links properly too.

2. Write a custom Docker volume driver (too ambitious and not 100% sure)
```
--mount 'type=volume,src=/,dst=/mnt/hostfs,volume-driver=mydriver,volume-opt=key1=value1,volume-opt=key2=value2'
```

3. Change utils container as a native launcher so it will has direct access the whole host filesystem by default.

**Comment by kilrau** [comment]
As just discussed, closing here in favor of the only remaining thing left: https://github.com/ExchangeUnion/xud-docker/issues/757

> * The macOS FUSE issue

Has separate issue: #756

> * Link file breaks on Linux (This happens on RaspiBlitz);

Edge case, we'll ignore this until it becomes an issue.

> * Read-write permission too wide for container usage (It's not normal to map "/" into contianers);

Separate issue: https://github.com/ExchangeUnion/xud-docker/issues/786

> * Cannot work on Windows without WSL2 (For more details, see [this SO question](https://stackoverflow.com/questions/64807757/how-to-mount-a-windows-path-volume-inside-a-docker-container));

We'll enforce WSL2 from now on (https://github.com/ExchangeUnion/xud-ui/issues/96).

> * Performance issue.

We'll ignore this one too until it becomes an issue.
