### ISSUE TITLE
Binary launcher MVP

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#788]
- run launcher, specify network (simnet, testnet, mainnet), cli commands: up, down, restart
- mount `C:/users/username/Appdata/Roaming/xud-docker`, backup path is set to this path for MVP too

**Comment by reliveyy** [comment]
```bash
./launcher -n simnet export ...
# generate docker-compose.yml file
./launcher -n simnet up 
# -> docker-compose -p simnet -f docker-compose.yml up -d
./launcher -n simnet start xud 
# -> docker-compose -p simnet -f docker-compose.yml start xud
./launcher -n simnet stop xud
# -> docker-compose -p simnet -f docker-compose.yml stop xud
./launcher -n simnet restart xud
# -> docker-compose -p simnet -f docker-compose.yml restart xud
./launcher -n simnet down
# -> docker-compose -p simnet -f docker-compose.yml down
```

Xud-docker home directories on different platforms

* Windows `C:\Users\<user>\AppData\Local\XudDocker`
* macOS `/Users/<user>/Library/Application Support/XudDocker`
* Linux `/home/<user>/.xud-docker`

**Comment by erkarl** [comment]
ACK
