### ISSUE TITLE
lndbtc stuck with `"synced_to_chain": false` on first run

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#82]
Can be solved by:
`simnet > restart lndbtc` 
`simnet > restart xud`

It takes several minutes after this until `lndbtc` gets a channel from the bot, so a bit annoying.

Here the full log of an `lndbtc` instance ending up stuck with `"synced_to_chain": false`:
[lndbtc.log](https://github.com/ExchangeUnion/xud-docker/files/3406206/lndbtc.log)

**Comment by kilrau** [comment]
Also happens on native setup: https://github.com/ExchangeUnion/xud-simnet/issues/41

Leaving this open here though.

**Comment by kilrau** [comment]
As a first step let's try with lnd 0.7 and see if the situation improves

**Comment by reliveyy** [comment]
Please re-check this issue becuase #107 had been merged

**Comment by kilrau** [comment]
Still the case, but handled by https://github.com/ExchangeUnion/xud-simnet/issues/41, closing here.
