### ISSUE TITLE
Ask before upgrading

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#86]
Instead of automatically updating when new images are available I'd prefer to have a notification: `A new version is available. Would you like to upgrade (Warning: this will restart your environment and cancel all open orders)? Y/n?`

**Comment by kilrau** [comment]
I was also a bit annoyed by docker doing `down`, `update`, `up` without asking for permission. This might kill orders you have open and we wouldn't want that. Let's do that!
