### ISSUE TITLE
Add default currencies + pairs to xud

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud-docker#9]
Offshoot from: https://github.com/ExchangeUnion/xud/pull/856
Depending on: https://github.com/ExchangeUnion/xud/pull/827

Enable the following trading pars when bootstrapping a new xud database (initial start):
- If lnd is enabled = LTC/BTC
- If lnd+raiden is enabled = LTC/BTC, WETH/BTC, LTC/WETH, BTC/DAI, LTC/DAI

**Raiden specific currencies are dependent on the contract address.**

**Comment by reliveyy** [comment]
@erkarl https://github.com/ExchangeUnion/xud-docker/blob/master/images/xud/entrypoint.sh#L14
This set_weth function copied xud-simnet-set-WETH script logic into xud image

**Comment by kilrau** [comment]
this issue is about setting testnet currencies. testnet ropsten weth/dai contract etc...

**Comment by kilrau** [comment]
Thinking about this again, I don't think checking availability of L2 client's first and enable pairs according to this is the right way. We'll do it the other way round - user selects currencies and we help getting according L2 clients running.

* DAI/WETH currencies will be added by https://github.com/ExchangeUnion/xud/issues/1114 on default.
* Handling adding other additional pairs and currencies after this will be done by https://github.com/ExchangeUnion/xud/issues/1111

Closing here.
