### ISSUE TITLE
Warning: insecure environment read function 'getenv' used

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#92]
Get rid of: `D0722 12:29:39.862267043     211 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used`

`Linux K-Yoga 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by reliveyy** [comment]
Releated to https://github.com/grpc/grpc/issues/8104

**Comment by reliveyy** [comment]
https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/env_linux.cc#L58

Alpine linux use musl instead of glibc. 

```
#elif __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 17)
  result = secure_getenv(name);
#else
  result = getenv(name);
```

So we can guess musl doesn't satisfy condition `__GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 17)`
